---
title: "Chomsky and Epstein [title needed]"
format: html
editor: visual
exec: false
---

Every year or two, I teach my students about the Vietnam War. In doing so, I ask these young people to read these words written by a forty-year-old college professor in 1968:

> "By entering into the arena of argument and counter-argument, of technical feasibility and tactics, of footnotes and citations, by accepting the presumption of legitimacy of debate on certain issues, one has already lost one’s humanity. This is the feeling I find almost impossible to repress when going through the motions of building a case against the American war in Vietnam. Anyone who puts a fraction of his mind to the task can construct a case that is overwhelming: surely this is now obvious. In a way, by doing so he degrades himself, and insults beyond measure the victims of our violence and our moral blindness. … The war is simply an obscenity, a depraved act by weak and miserable men, including all of us, who have allowed it to go on and on with endless fury and destruction – all of us who would have remained silent had stability and order been secured. It is not pleasant to use such words, but candor permits no less.”

The professor was Noam Chomsky, then a rising star in linguistics. *American Power and the New Mandarins*, which includes this paragraph in its introduction, was his first political book. After our deep dive into the actual mechanisms of that war, its tactics and tremendous human toll, my students are left struggling to make sense of systematic cruelty. Chomsky’s words land with that basic need to find someone willing to stand up and say no.

Arguably, it was those words, and those of a handful of other anti-war academics, that convinced Daniel Ellsberg to leak the Pentagon Papers, a decade of behind-the-scenes documenation of elite decisionmaking over the wor, filled with deceptions of self and the American public. One of Chomsky's next books would be a detailed analysis of the Papers, and Chomsky and Ellsberg would join the same affinity group for the May Day 1971 protests against the war.

But, of course, that phrase “a depraved act by weak and miserable men” has been echoing in my head this week for a very different reason. Amid the further revelations around serial sex trafficker and orchestrator of abuse of girls Jeffrey Epstein is [abundant correspondence attesting to his close friendship with Noam Chomsky](https://www.theguardian.com/us-news/2026/feb/03/epstein-files-noam-chomsky). The core facts of this friendship were set out in a detailed [letter from Chomsky attesting to it](https://www.wbur.org/news/2025/11/20/emails-epstein-mit-harvard-trump-chomsky) sometime after 2017, which leaked last November.

> “The impact of Jeffrey's limitless curiosity, extensive knowledge, penetrating insights, and thoughtful appraisals is only heightened by his easy informality, without a trace of pretentiousness. He quickly became a highly valued friend and regular source of intellectual exchange and stimulation.”

But now we know that friendship was repeatedly reaffirmed even as investigative reporting exposed Epstein as a frequent abuser of children. In separate emails on November 30, 2018, Noam and his wife Valeria each said (quoting Noam here), "[We] just want to tell you that it's one of the great experiences of our life to have you as a friend, and to remain so and cherish this permanent relationship."

Those of us who have learned from Chomsky, and especially who have admired his persistent work to expose American imperial machinations from East Timor to Israel/Palestine to Central America (as [celebrated by Arundhati Roy in 2003](http://www.rarre.org/documents/roy/The%20Loneliness%20Of%20Noam%20Chomsky.pdf)); and his persistence as a frequently self-effacing moral critic (as [valorized by Fred Branfman in 2012](https://www.salon.com/2012/06/17/when_chomsky_wept/)) are naturally going through shock. Some have done their best to [sympathetically imagine what Chomsky didn't know](https://www.thenation.com/article/society/noam-chomsky-jeffrey-epstein-emails/) (in this scholarly accounting by Greg Grandin). “Over his long life, Noam Chomsky … has suffered fools, knaves, and hangers-on, both the curious and criminal, too lightly,” Grandin wrote. It now seems that moment is passing and we are all left with profound and bereft disappointment [expressed this week by Chomsky's last co-author](https://www.counterpunch.org/2026/02/03/on-the-emails-between-jeffrey-epstein-and-noam-chomsky/), Vijay Prashad: “Since Noam cannot speak or write and explain his relationship with Epstein, the matter is fraught. There is nothing to say on his behalf.”

Jeffrey Epstein was a man who seems to have turned sexual abuse into currency among the unimaginably wealthy and politically powerful, and who in turn collected closeness to fame as something of a currency. In another letter, and these texts seem to have had a strange significance for Epstein, former Israeli Prime Minister Ehud Barak and his wife Nili Priel [called him](https://www.nytimes.com/2025/08/05/us/jeffrey-epstein-mansion-photos.html) a "A COLLECTOR OF PEOPLE." A symbolic instantiation of this is Epstein’s collection of photographs of himself and famous people: in the New York Times photo of this display, Noam Chomsky, his wife Valeria, and Epstein walk hand-in-hand in one frame, set among others featuring Fidel Castro, Elon Musk, and Richard Branson.

This is the world Chomsky walked into, one of private planes, private dinners with Woody Allen and (his stepdaughter-turned-wife) Soon-Yi Previn, and luxury apartments in Paris and New York. Oh, and the opportunity to meet Ehud Barak and Steve Bannon. The specifics of the Chomsky–Allen–Epstein evening are probably known to just a small circle, but the vibe of the home (toured and [photographed by the *New York Times*](https://www.nytimes.com/2025/08/05/us/jeffrey-epstein-mansion-photos.html) in 2025) lines up with Allen's description of Epstein gatherings in general:

> Wide variety of interesting people at every dinner just about. Politicians, scientists, teachers, magicians, comedians, intellectuals, journalists, an entomologist, a concert pianist. Anyhow, it's always interesting and the food is sumptuous and abundant. Lots of dishes, plenty of choices, numerous desserts, well served. I say well served - often it's by some professional houseman and just as often by several young women reminding one of Castle Dracula where Lugosi has three young female vampires who service the place. (typewritten, signed letter from Allen for Epstein's 63rd birthday in 2016)

One has to imagine Noam Chomsky perhaps ascending the staircase of Epstein's palatial apartment whose signature touches included [this female statue in a wedding dress hanging on a rope](https://commons.wikimedia.org/wiki/File:EFTA00000930_-_Bronze_sculpture_of_a_woman_in_a_white_veil_hangs_from_the_ceiling_suspended_over_a_grand_staircase_with_ornate_railings.jpg) and a first-edition copy of *Lolita*. Or boarding a private airplane to chat with Steve Bannon. Where in this was his curious mind and much vaunted conscience? Did he perceive the circling exchange of fame as currency? Did he not wonder whether all this opulence, with its misogynist accents, was concealing something something abominable?

By Chomsky's own writings, billionaire status was itself scandalous:

> The very idea that there should be a certain class of people who give orders by virtue of their ownership of wealth and another huge class who take on orders and follow them because of their lack of access to wealth and power, that's unacceptable. So, sure it should be abolished. ([Interview](https://web.archive.org/web/20210509175625/http://pennpoliticalreview.org/2017/01/interview-noam-chomsky/), 2017)

As Vijay Prashad writes, “Epstein was a man of the Far Right and a Zionist – an accumulator of men of power and influence who want to turn the world into their paradise and our hell.”

But the real scandal of Jeffrey Epstein was of course his sex trafficking empire, which ensnared hundreds and likely over 1,000 girls and women. Rumors of Epstein's Caribbean Island have circulated for years, tainting politicians he was closely acquainted with, not least presidents Bill Clinton and Donald Trump. The question becomes, how could Chomsky coexist with this possibility, allow it to go on? How could he not have perceived that his own fame and friendship, his own letter and signature, as potentially a cover for this man?

"You are like a closed book to many of them but you know everything about everyone,” Ehud Barak wrote in his birthday letter to Epstein. Was he a man who knew, or chose not to know? Donald Trump was more forthright, “We have certain things in common, Jeffrey. … May every day be another wonderful secret.”

Chomsky's [letter](https://media.wbur.org/wp/2025/11/HOUSE_OVERSIGHT_022405.pdf) by contrast, speaks of no secrets, and remains decidedly above the belt. But in the context of all that has been revealed about Epstein, that very silence speaks volumes. If he knew, or even deeply suspected, this was willful “moral blindness.” Again the echo from Chomsky in 1968: “In a way, by doing so he degrades himself, and insults beyond measure the victims.”

And now, with the latest round of documents, we know he knew the story. And that he also was willful in his attempts to deny what was being [reported in November 2018, with abundant witness testimony and a suspended federal indictment as evidence](https://www.miamiherald.com/news/local/article219494920.html). Epstein wrote to Chomsky complaining of the coverage, grasping at his connections as a defense “Can use some advice. The press is painting me as a monster. … Being fed by plaintiffs. lawyers. only wanting money. i have no skill with the general public or media. . should ken starr write an editorial? a scientist. . who as benefited\[?\]” Chomsky replied “We've seen some of it. Disgusting. Particularly in this culture of gossip-mongers” and pledged “real friendship, deep and sincere and everlasting from both of us” on December 7.

Two more months pass and Chomsky writes to Epstein that the latter's “Awful situation is always on my mind. And to a much lesser degree, Lawrence too and other cases that I know about.” Chomsky advises ignoring the accusations. But then he turns to the particular challenge of these accusations coming in the midst of the #MeToo movement:

> What the vultures dearly want is a public response, which then provides a public opening for an onslaught of venomous attacks, many from just publicity seekers or cranks of all sorts -- which are impossible to answer (how do you prove that you are not a neo-Nazi who wants to kill the Jews, or a rapist, or whatever charge comes along?). That's particularly true now with the hysteria that has developed about abuse of women, which has reached the point that even questioning a charge is a crime worse than murder. For virtually everyone who sees any of this, the reaction will be "where there's smoke there's fire, maybe raging fire" (whatever the facts, which few will even think of investigating).\
> In general, it's best I think not to react unless directly questioned, particularly in the current mood -- which, I presume, will fade away, even if not in time to prevent much torture and distress.

It is clear that either Chomsky was engaging in profound denial about the actions of his friend, or worse, that he regarded them as peripheral to Epstein's life, personal matters with no public import. “Torture and distress” in Chomsky’s letter happen not to the victims of sexual abuse, but to its alleged perpetrators. [Recurrent sexual banter in correspondence](https://www.theguardian.com/us-news/2026/feb/03/epstein-files-noam-chomsky) from this known abuser never seems to have put Chomsky off the friendship.

Even more troubling is the wholesale attack on the "hysteria" of MeToo. What a choice of word, that alone is rightly damning. And what a lack of curiosity about a social moment that revealed the widespread existence of sexual assault at all levels of American life, and literally scores of circles of sexual abuse and silence in multiple domains of society, not least Hollywood and universities. The fact that Chomsky, Epstein, and Bannon are circulating alongside each other at this exact moment and that Chomsky can play the *eminence grise*, scoffing at a moment of generational awakening to a too-often-hidden form of power is gut-wrenching to those of us who have valued his opinion elsewhere.

Chomsky had worked, or at least published, within a milieu that understood the intertwined nature of political power, economic accumulation, and sexist domination for decades at this point. South End Press made him a co-author to *Liberating Theory* in the 1980s, a text that was fully intersectional in its analysis of class, race, gender and authority, *avant la lettre* -- though not before groups like the [Combahee River Collective](https://blackpast.org/african-american-history/combahee-river-collective-statement-1977/) had of course gotten then long before. (Yet it must be said that Chomsky failed for decades to thoroughly incorporate a gendered perspective into his writing, somehow failing to pick up this thread in analyzing antagonists like Henry Kissinger.)

The firewall between personal failure and political wisdom must break here. Chomsky's failure of judgement here is not just about a (horrifyingly embarrassing) friendship but about a political moment. And in breaking that wall, we encounter other such choices and silencings: Chomsky's denials of genocide in Cambodia and the Balkans perhaps rise to the top.

I will, I think, still share the words of the outraged young professor Chomsky when I teach the Vietnam War. But I regard the generational refusal of #MeToo as just as pivotal as the antiwar movement a half century before it. And I'll teach the voices of that movement, their insights and theories. This frustrating, pointless set of choices by someone who earned their heroic status in the eyes of many is also a cultural text worth puzzling over. Perhaps the answers to those of us asking "why?" will teach us something. Or at least, we can rediscover the moral imperative to not lose sight of personal cruelty when you spend your life fighting systems of violence. And we'll learn something about the kinds of flattery that wealth can buy, and why we can and should refuse it.

We've learned a lot in the decade since Steve Bannon led and won a campaign to make a known sexual abuser into president of the United States. And much of this knowledge comes from personal testimony, given in many public and private ways, and reaching a remarkable crescendo that echoed in every institution of American life. More of it comes from the dogged, fact-based, and persistent reporting by writers like Jane Mayer and Jill Abramson (for whom Harvey Weinstein's case marked a second generation of their investigative reporting of sexual abuse by the powerful), like Julie Brown (whose careful journalistic sourcing of her claims about Jeffrey Epstein should have been trustworthy to Chomsky), and like Ronan Farrow (whose take on his abusive father Woody Allen should have resonated). And numerous scholars from Cynthia Enloe to Kate Manne, from June Jordan to Saadiya Hartman have highlighted the intimate connections between interpersonal abuse and societal power.

Even fifty-six years ago, at the publication of Chomsky's *American Power and the New Mandarins*, the power of our government was not just about empire and economy, but also about the comradery of elite men, the recruitment of masculine ideals to send young men to kill and die, the fear of being seen as wrong or weak. You can now go back and [hear in his own words how LBJ escalated](https://www.pbs.org/moyers/journal/11202009/profile.html) the Vietnam War out of fear as being called weak by his political opponents. And how architect of intensified bombing Henry Kissinger called power “the ultimate aphrodesiac.” American “mandarins,” which is to say intellectuals in universities and government departments, were and are—all too often—weak and miserable men, being led by their need to prove themselves, impress others, and cultivate status as they make choices with irreparable consequences for our society and others. How much stronger an analysis of empire, of American elites, and of militarism would come from someone who read as much as Chomsky but took sexist power, masculinity, and widespread abuse by those in authority seriously?
