project: 
  type: website
  output-dir: docs
  resources: 
    - images/*
    
pagetitle: "{{< meta title >}} | Carwil Bjork-James"
    
website: 
  page-navigation: true
  title: "Carwil Bjork-James"
  site-url: "https://carwilb.github.io/quarto-website" 
  favicon: favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "Carwil Bjork-James's research and data science website"
    
  sidebar:
    logo: "images/carwil-bjork-james-hex.png"
    logo-alt: "Carwil Bjork-James in a data science hexagon"
    title: "Carwil Bjork-James"
    subtitle: "Research notes on violence, human rights, social movements, and open data"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://ultimateconsequences.github.io
        text: "Ultimate Consequences Project Website"
      - icon: wordpress
        href: https://woborders.blog
        text: "Carwil without Borders"
      - icon: mastodon
        href: https://mastodon.online/@Carwil
        text: "Carwil on Mastodon"
      - icon: twitter
        href: https://twitter.com/CarwilBJ
        text: "Carwil Bjork-James on Twitter" 
      - icon: twitter
        href: https://carwilb.github.io/twitter
        text: "Twitter archive" 

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Welcome
      - text: "---"
      - href: about-bio.qmd
        text: "Biography"
      - text: "---"
      - href: index.qmd
        text: Posts
        contents: posts/*

format:
  html:
    theme: 
      light: cosmo
      dark: slate
    mainfont: "Source Sans Pro"
    code-copy: true
    code-overflow: wrap
    toc: false
    citation-style: csl/chicago-notes.csl
    link-citations: false

filters:
  - include-files.lua


  
