{
  "hash": "07130df9436bb152cb187de74e06473f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Unreported Detention: Un- and under-reported ICE facilities\" \nsubtitle: \"An analysis of ICE detention statistics not included in the FY 2025 annual detention report\"\ndescription: \"Comparing the Deportation Data Project's daily detention counts with ICE's published annual statistics to identify unreported facilities and track population changes\"\nauthor: \"Carwil Bjork-James\"\ndate: last-modified\nimage: ddp-comparison-thumbnail.png\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n## Overview\n\nThis page offers an analysis of two forms of data on the population of people held by US Immigration and Customs Enforcement (ICE): summary data on detention published by ICE on its website and a detailed and granular dataset of arrests, removals, and overnight populations under ICE custody, released under the Freedom of Information Act and archived by the Deportation Data Project.\n\nThe former data, is published online the [ICE Detention Management Division](https://www.ice.gov/detain/detention-management). I have also produced a map of reported facilities based on sixteen years of reporting (eight annual reports and two summary sheets) from ICE.\n\nThe newer data covers \"every ICE encounter, detainer request, arrest, book-in to detention, and removal\" between September 1, 2022 and October 15, 2025.\n\nAs becomes clear below, the more extensive data shows that ICE's public reporting is incomplete, and the uncounted population grew massively during 2025, from hundreds of individuals per night in the final months of the Biden administration to as many as forty-five hundred individuals, and frequently in excess of three thousand in summer and early fall 2025. This unreported network includes over ICE-owned holding facilities, nine dedicated ICE detention centers, local jail and state prisons, federal prisons, and over 200 medical facilities.\n\nThe FOIA-supplied data also exceeds ICE's annual reporting in those facilities that do match by 1,038 detainees per night over the course of FY 2025, though this only amounts to 2% of the total population.\n\nIn much oyf this report, facility-level summaries distinguish between facilities with **Peak Population ≥ 2** and those with **Peak Population \\< 2**. Facilities with no more than one detainees at a time account for many DDP facility codes but negligible population. Separating them keeps attention on facilities with substantive detention activity.\n\n*This page is part of a larger data project to gather, summarize, and analyze public data about immigration enforcement in the United States. The focus here is detention facilities used by US Immigration and Customs Enforcement (ICE).*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(dplyr)\nlibrary(tidyr)\nlibrary(ggplot2)\nlibrary(scales)\nlibrary(knitr)\nlibrary(sf)\nlibrary(leaflet)\nlibrary(leafpop)\nlibrary(kableExtra)\nlibrary(leaflet.extras)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Pre-computed data from the ice-detention pipeline.\n# Run copy-data.sh to refresh from the pipeline project.\nice_fy25          <- readRDS(\"data/ice_fy25.rds\")\nddp_fy25          <- readRDS(\"data/ddp_fy25.rds\")\nddp_fy25_keyed    <- readRDS(\"data/ddp_fy25_keyed.rds\")\ndaily_totals      <- readRDS(\"data/daily_totals.rds\")\nunmatched         <- readRDS(\"data/unmatched.rds\")\ndaily_unmatched   <- readRDS(\"data/daily_unmatched.rds\")\nmonthly_unmatched <- readRDS(\"data/monthly_unmatched.rds\")\npeak_fy25         <- readRDS(\"data/peak_fy25.rds\")\nbiden_unmatched   <- readRDS(\"data/biden_unmatched.rds\")\ntrump_unmatched   <- readRDS(\"data/trump_unmatched.rds\")\ndaily_unreported  <- readRDS(\"data/daily_unreported.rds\")\n```\n:::\n\n\n## Aggregate comparison\n\nThe DDP data (Deportation Data Project) provides daily facility-level detention counts. To compare with the ICE FY25 annual statistics, we average DDP daily counts from October 1, 2024 through September 24, 2025---the date stamp on the FY25 spreadsheet. On average, the DDP data reflects 2581 more detainees per day than reported in the ICE FY25 annual statistics. As we'll see below, about 1,000 of these detainees are in facilities that appear in both sources but with higher counts in the DDP data. The rest are in facilities that do not appear at all in the ICE FY25 spreadsheet, accounting for a full-year average of roughly fifteen-hundred detainees per day. However, since the unmatched population grew dramatically during 2025, the daily unmatched population was much higher towards the end of the year.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  Source      = c(\"ICE FY25 annual stats\", \"DDP daily average\"),\n  Facilities  = c(nrow(ice_fy25), nrow(ddp_fy25)),\n  `Total ADP` = c(round(sum(ice_fy25$ice_adp, na.rm = TRUE)),\n                   round(sum(ddp_fy25$ddp_adp)))\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Source                | Facilities| Total ADP|\n|:---------------------|----------:|---------:|\n|ICE FY25 annual stats |        189|     47549|\n|DDP daily average     |        768|     50130|\n\n\n:::\n:::\n\n\nThe DDP covers 768 facility codes while the ICE spreadsheet lists 189 facilities. The DDP's higher total reflects the many additional facilities (hold rooms, federal prisons, medical facilities) not included in the ICE annual statistics.\n\n### Daily population over time\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfy_breaks <- as.Date(c(\"2023-10-01\", \"2024-10-01\", \"2025-10-01\"))\nfy_labels <- data.frame(\n  x = as.Date(c(\"2024-04-01\", \"2025-04-01\", \"2025-10-08\")),\n  label = c(\"FY24\", \"FY25\", \"FY26\")\n)\n\nggplot(daily_totals, aes(x = date, y = total_pop)) +\n  geom_line(linewidth = 0.3) +\n  geom_vline(xintercept = fy_breaks, linetype = \"dashed\", alpha = 0.4) +\n  # Annual averages as calculated as follows\n  # facilities_aggregated$FY24$sum_criminality_levels |> sum()\n  # 36276.8\n  # facilities_aggregated$FY25$sum_criminality_levels |> sum()\n  # 47550.2\n  # facilities_aggregated$FY26$sum_criminality_levels |> sum() # taken with February 2026 data\n  # 66811.9\n  # geom_segment(x=as.Date(\"2023-10-01\"), xend=as.Date(\"2024-10-01\"), \n  #              y=36276.8, linetype = \"dashed\", alpha = 0.4, linewidth=0.1, color = \"blue\") +\n  # geom_segment(x=as.Date(\"2024-10-01\"), xend=as.Date(\"2025-10-01\"),\n  #              y=47550.2, linetype = \"dashed\", alpha = 0.4, linewidth=0.1, color = \"blue\") +\n  # geom_segment(x=as.Date(\"2025-10-01\"), xend=as.Date(\"2025-11-01\"),\n  #              y=66811.9, linetype = \"dashed\", alpha = 0.4, linewidth=0.3, color = \"blue\") +\n  geom_text(data = fy_labels, aes(x = x, y = max(daily_totals$total_pop) * 1.04,\n                                   label = label), inherit.aes = FALSE, size = 3) +\n  scale_y_continuous(labels = comma) +\n  labs(x = NULL, y = \"Total detained population\")\n```\n\n::: {.cell-output-display}\n![Total ICE detained population per day (DDP data, all facilities)](index_files/figure-html/fig-daily-total-1.png){#fig-daily-total width=672}\n:::\n:::\n\n\n## Facility-level matching\n\nICE uses detainee locator codes, or DETLOCs to keep track of which facilities detainees are housed in. These codes are included in 2015 and 2017 facility lists (describing ICE detention populations from FY 2010 to 2017), in a list maintained by the Deportation Data Project, and in separate lists compiled by the Vera Institute and The Marshall Project. Our data wrangling matched the FY 2019-2026 data to these other lists by exact facility name, address, city and state, and other criteria. All 189 detention facilities listed in the ICE spreadsheet for FY2025 have one or more known DETLOC.\n\nWe join the two datasets through canonical facility IDs. Each DDP facility code is mapped to a canonical ID via `detloc_lookup_full`, which preserves all DETLOC variants from every source (DMCP, DDP, hold/ERO, Vera). Some canonical facilities have multiple codes---for example, Central Arizona Florence Correctional Complex uses `CCADCAZ` (DMCP) and `CCAFLAZ` (DDP), and Delaney Hall uses `ESSEXNJ` (DMCP) and `DHDFNJ` (DDP). Using the full lookup ensures all codes contribute ADP to the correct facility.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Aggregate DDP by canonical_id for matched facilities.\nddp_by_canonical <- ddp_fy25_keyed |>\n  filter(in_ice_fy25) |>\n  group_by(canonical_id) |>\n  summarise(ddp_adp = sum(ddp_adp), .groups = \"drop\")\n\ncomparison <- ice_fy25 |>\n  # ICE FY25 can have multiple rows per canonical_id (e.g., Adelanto + Desert View Annex)\n  group_by(canonical_id) |>\n  summarise(\n    canonical_name = first(canonical_name),\n    ice_adp = sum(ice_adp, na.rm = TRUE),\n    .groups = \"drop\"\n  ) |>\n  full_join(ddp_by_canonical, by = \"canonical_id\") |>\n  mutate(\n    in_ice = !is.na(ice_adp),\n    in_ddp = !is.na(ddp_adp),\n    diff   = ddp_adp - ice_adp,\n    pct_diff = diff / ice_adp * 100\n  )\n\nmatched <- comparison |> filter(in_ice & in_ddp)\n\ntibble(\n  Category = c(\"In both sources\", \"ICE only (no DDP match)\",\n               \"Matched: ICE total ADP\", \"Matched: DDP total ADP\",\n               \"Matched: aggregate difference\"),\n  Value = c(\n    sum(comparison$in_ice & comparison$in_ddp),\n    sum(comparison$in_ice & !comparison$in_ddp),\n    round(sum(matched$ice_adp, na.rm = TRUE)),\n    round(sum(matched$ddp_adp, na.rm = TRUE)),\n    paste0(round(sum(matched$ddp_adp, na.rm = TRUE) -\n                   sum(matched$ice_adp, na.rm = TRUE)),\n           \" (\", round((sum(matched$ddp_adp, na.rm = TRUE) /\n                           sum(matched$ice_adp, na.rm = TRUE) - 1) * 100, 2), \"%)\")\n  )\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Category                      |Value        |\n|:-----------------------------|:------------|\n|In both sources               |188          |\n|ICE only (no DDP match)       |0            |\n|Matched: ICE total ADP        |47549        |\n|Matched: DDP total ADP        |48586        |\n|Matched: aggregate difference |1037 (2.18%) |\n\n\n:::\n:::\n\n\n### Facility-level agreement\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboth_nonzero <- matched |> filter(ice_adp > 0, ddp_adp > 0)\n\nggplot(both_nonzero, aes(x = ice_adp, y = ddp_adp)) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  geom_point(alpha = 0.6) +\n  scale_x_log10(labels = comma) +\n  scale_y_log10(labels = comma) +\n  labs(x = \"ICE FY25 ADP (annual stats)\", y = \"DDP mean daily population\")\n```\n\n::: {.cell-output-display}\n![FY25 ADP comparison by facility (log scale). Dashed line = perfect agreement.](index_files/figure-html/fig-scatter-1.png){#fig-scatter width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntibble(\n  `Agreement band` = c(\"Within 10%\", \"Within 25%\", \"Within 50%\", \">50% difference\", \"Annual report shows greater value\"),\n  Facilities = c(\n    sum(abs(both_nonzero$pct_diff) <= 10),\n    sum(abs(both_nonzero$pct_diff) > 10 & abs(both_nonzero$pct_diff) <= 25),\n    sum(abs(both_nonzero$pct_diff) > 25 & abs(both_nonzero$pct_diff) <= 50),\n    sum(abs(both_nonzero$pct_diff) > 50),\n    sum(both_nonzero$pct_diff < 0)\n  )\n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Agreement band                    | Facilities|\n|:---------------------------------|----------:|\n|Within 10%                        |        115|\n|Within 25%                        |         26|\n|Within 50%                        |         30|\n|>50% difference                   |         17|\n|Annual report shows greater value |         24|\n\n\n:::\n:::\n\n\nAmong the 188 matched facilities with nonzero ADP in both sources, 115 agree within 10%. The log-scale correlation is 0.998. There are 24 facilities with a lower count in the DDP data and the largest percentage difference in this direction is -4.2%.\n\n\n::: {#tbl-ice-only .cell tbl-cap='ICE FY25 facilities with no DDP match'}\n\n```{.r .cell-code}\nice_only <- comparison |> filter(in_ice & !in_ddp)\nif (nrow(ice_only) > 0) {\n  ice_only |>\n    select(canonical_id, canonical_name, ice_adp) |>\n    mutate(ice_adp = round(ice_adp)) |>\n    arrange(desc(ice_adp)) |>\n    kable(col.names = c(\"ID\", \"Facility\", \"ICE ADP\"))\n}\n```\n:::\n\n\nAll ICE FY25 facilities have a matching DDP facility code.\n\n## Unmatched facilities {#sec-unmatched}\n\n**576** of 768 DDP facility codes do not appear in the ICE FY25 annual statistics. These are facilities where ICE holds detainees but which are excluded from the published spreadsheet.\n\n### By facility type\n\nFacility types are drawn from the Vera Institute's classification system. \"Dedicated\" facilities are purpose-built or contractually dedicated to ICE detention. \"Non-Dedicated\" are county jails and other facilities that also hold ICE detainees. \"Hold/Staging\" are short-term ERO processing rooms. \"Federal\" includes BOP prisons and USMS facilities.\n\n\n::: {#tbl-unmatched-types .cell tbl-cap='DDP facilities not in ICE FY25, by Vera facility type and ADP class'}\n\n```{.r .cell-code}\nunmatched |>\n  group_by(type_grouped, peak_class) |>\n  summarise(\n    Facilities = n(),\n    `FY25 ADP` = round(sum(ddp_adp)),\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(`FY25 ADP`)) |>\n  kable(col.names = c(\"Facility type\", \"Peak class\", \"Facilities\", \"FY25 ADP\"))\n```\n\n::: {.cell-output-display}\n\n\n|Facility type |Peak class | Facilities| FY25 ADP|\n|:-------------|:----------|----------:|--------:|\n|Hold/Staging  |Peak ≥ 2   |        169|     1163|\n|Dedicated     |Peak ≥ 2   |          2|      170|\n|Unclassified  |Peak ≥ 2   |        135|      140|\n|Federal       |Peak ≥ 2   |         24|       31|\n|Non-Dedicated |Peak ≥ 2   |         23|       30|\n|Unclassified  |Peak < 2   |        185|        6|\n|Non-Dedicated |Peak < 2   |         14|        2|\n|Medical       |Peak ≥ 2   |          1|        1|\n|Family/Youth  |Peak < 2   |          1|        0|\n|Family/Youth  |Peak ≥ 2   |          1|        0|\n|Federal       |Peak < 2   |         13|        0|\n|Hold/Staging  |Peak < 2   |          7|        0|\n|Medical       |Peak < 2   |          1|        0|\n\n\n:::\n:::\n\n\nThe 576 unmatched facilities account for a full-year ADP of roughly **1,544**. There were 475 facilites that averaged fewer than 2 detainees per day, contributing 136 ADP in total. Among them, 221 facilities never had more than 1 detainee per day, contributing 8 ADP in total.\n\n\n\n### Daily and monthly detention in unmatched facilities\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(daily_unmatched, aes(x = date, y = total_pop)) +\n  geom_line(linewidth = 0.3) +\n  scale_y_continuous(labels = comma) +\n  scale_x_date(date_labels = \"%b %Y\", date_breaks = \"2 months\") +\n  labs(x = NULL, y = \"Detained population (unmatched facilities)\")\n```\n\n::: {.cell-output-display}\n![Daily detained population in facilities not in ICE FY25 annual statistics](index_files/figure-html/fig-daily-unmatched-1.png){#fig-daily-unmatched width=672}\n:::\n:::\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmonthly_by_type <- monthly_unmatched |>\n  group_by(month, type_grouped) |>\n  summarise(daily_avg = sum(n_detained) / n_distinct(date), .groups = \"drop\")\n\nggplot(monthly_by_type, aes(x = month, y = daily_avg, fill = type_grouped)) +\n  geom_col() +\n  scale_y_continuous(labels = comma) +\n  scale_x_date(date_labels = \"%b %Y\", date_breaks = \"2 months\") +\n  labs(x = NULL, y = \"Average daily population\", fill = \"Facility type\")\n```\n\n::: {.cell-output-display}\n![Average daily population in unmatched facilities, by month and type](index_files/figure-html/fig-monthly-by-type-1.png){#fig-monthly-by-type width=672}\n:::\n:::\n\n\n### Last 60 days of FY25\n\nThe final 60 days of the FY25 data window (July 27 -- September 24, 2025) capture the period of peak detention.\n\n\n::: {#tbl-last60 .cell tbl-cap='Average daily population in unmatched facilities, last 60 days of FY25'}\n\n```{.r .cell-code}\nlast60_start <- as.Date(\"2025-07-27\")\nlast60_end   <- as.Date(\"2025-09-24\")\n\nlast60 <- monthly_unmatched |>\n  filter(date >= last60_start, date <= last60_end)\n\nnon_empty <- last60 |>\n  group_by(detention_facility_code) |>\n  summarise(total_detained = sum(n_detained), .groups = \"drop\") |>\n  filter(total_detained > 0)\n\nlast60_by_type <- last60 |>\n  filter(detention_facility_code %in% non_empty$detention_facility_code) |>\n  group_by(type_grouped) |>\n  summarise(\n    Facilities = n_distinct(detention_facility_code),\n    `Daily avg` = round(sum(n_detained) / n_distinct(date)),\n    .groups = \"drop\"\n  ) |>\n  arrange(desc(`Daily avg`))\n\nlast60_total <- sum(last60_by_type$`Daily avg`)\n\nlast60_by_type |>\n  rename(`Facility type` = type_grouped) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Facility type | Facilities| Daily avg|\n|:-------------|----------:|---------:|\n|Hold/Staging  |        162|      1987|\n|Dedicated     |          2|       692|\n|Unclassified  |        180|       334|\n|Federal       |         30|        75|\n|Non-Dedicated |         22|        52|\n|Medical       |          2|         2|\n|Family/Youth  |          1|         0|\n\n\n:::\n:::\n\n\nIn the last 60 days, **3,142** people per day were held in facilities absent from the ICE FY25 annual statistics.\n\n### Peak FY25 population by facility\n\nThis table of the facilities with the largest peak population in FY 2025 help us make sense of th unreported population. A variety of different kinds of facilities play a roll:\n\n* New Federal facilities like the El Paso Soft-Sided Facility (`ELPASOFS`), which is distinct from the El Paso Processing Center (`EPC`) and Camp East Montana (`EROFCB`), held large numbers of detainees. This new facility was not added to the FY2025 statistics and was supplanted by Camp East Montana before the new fiscal year. The Ursula Centralized Processing Center, formally associated with Customs and Border Patrol, is listed as holding an average of 32 and a mamximum of 463 ICE detainees.\n\n* Dedicated ICE detention centers supplied by states, like the Baker Correctional Institution (`FLBAKCI`), a Florida state prison that was turned over to use by ICE in 2025, and held as many as 294 prisoners in FY 2025. The Florida Soft-Sided Facility (`FLDSSFS`, also known as Alligator Alcatraz was the sceond largest unreported facility, with a peak population of 1,482 detainees on July 30, 2025. These facilities were added to the FY 2026 statistics but left off the 2025 document.\n\n* Holding facilities associated with airports like the Krome Hold Room (`KROHOLD`) near Miami International Airport. This was one of the few facilities used at a large scale in the final days of the Biden administration. The Arizona Removal Operations Coordination Center (AROCC) operates at the Phoenix-Mesa Gateway Airport. As with other hold rooms, these facilities were reportedly exceeding the 12-hour limit on detention time. \n\n* Field Offices and Sub-Offices of the Enforcement and Removal Operations (ERO) division of ICE, which are not designed for long-term detention but which held large numbers of detainees during the surge in 2025. This shift coincided with new ICE guidance authorizing detention up to 72 hours, but preceded the new permission and exceeded its limits.\n\n* A handful of local prisons were used to hold ICE detainees en masse, including the Richwood Correctional Center (`RICHWOOD`) in Louisiana, which held up to 1,200 detainees at a time.\n\n\n::: {#tbl-peak-top20 .cell tbl-cap='Top 20 unmatched facilities by FY25 peak detained population'}\n\n```{.r .cell-code}\npeak_fy25 |>\n  arrange(desc(peak_pop)) |>\n  head(20) |>\n  select(detention_facility, state, type_grouped, peak_pop, peak_date, mean_pop) |>\n  kable(col.names = c(\"Facility\", \"State\", \"Type\", \"Peak\", \"Peak date\", \"Mean ADP\"))\n```\n\n::: {.cell-output-display}\n\n\n|Facility                           |State |Type         | Peak|Peak date  | Mean ADP|\n|:----------------------------------|:-----|:------------|----:|:----------|--------:|\n|EL PASO SOFT SIDED FACILITY        |TX    |Hold/Staging | 1606|2025-08-12 |    243.2|\n|FLORIDA SOFT-SIDED FACILITY-SOUTH  |FL    |Dedicated    | 1482|2025-07-30 |    170.3|\n|KROME HOLD ROOM                    |FL    |Hold/Staging |  600|2025-02-17 |     36.5|\n|URSULA CENTRALIZED PROCESSING CNTR |TX    |Unclassified |  463|2025-07-11 |     31.6|\n|LOS CUST CASE                      |CA    |Hold/Staging |  455|2025-07-11 |     58.7|\n|BAKER C. I.                        |FL    |Unclassified |  294|2025-09-24 |     15.7|\n|RICHMOND SUB-OFFICE HOLD           |VA    |Hold/Staging |  277|2025-09-07 |     16.2|\n|BROADVIEW SERVICE STAGING          |IL    |Hold/Staging |  245|2025-09-20 |     31.7|\n|NYC HOLD ROOM                      |NY    |Hold/Staging |  228|2025-06-05 |     40.9|\n|DALLAS F.O. HOLD                   |TX    |Hold/Staging |  225|2025-09-18 |     53.1|\n|MONTGOMERY HOLD RM                 |TX    |Hold/Staging |  221|2025-08-21 |     50.0|\n|BOSTON HOLDROOM                    |MA    |Hold/Staging |  206|2025-05-13 |     18.6|\n|AZ REM OP COORD CENTER (AROCC)     |AZ    |Hold/Staging |  195|2025-04-30 |     37.4|\n|MIAMI STAGING FACILITY             |FL    |Hold/Staging |  176|2025-01-31 |     16.5|\n|ATLANTA DIST. HOLD RM              |GA    |Hold/Staging |  168|2025-06-25 |     42.1|\n|SANTA ANA DRO HOLDROOM             |CA    |Hold/Staging |  150|2025-06-11 |     11.3|\n|SAN ANTONIO DRO HOLD ROOM          |TX    |Hold/Staging |  145|2025-06-04 |     19.6|\n|INDIANAPOLIS HOLD ROOM             |IN    |Hold/Staging |  130|2025-09-19 |     12.3|\n|WASHINGTON FIELD OFFICE            |VA    |Hold/Staging |  127|2025-08-23 |     17.3|\n|ORLANDO HOLD ROOM                  |FL    |Hold/Staging |  126|2025-06-04 |     19.6|\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npeak_fy25 |>\n  filter(peak_pop > 0) |>\n  ggplot(aes(x = peak_pop)) +\n  geom_histogram(bins = 40) +\n  scale_x_log10(labels = comma) +\n  labs(x = \"Peak detained population (FY25)\", y = \"Facilities\")\n```\n\n::: {.cell-output-display}\n![Distribution of FY25 peak population among unmatched facilities (log scale, facilities with peak > 0)](index_files/figure-html/fig-peak-dist-1.png){#fig-peak-dist width=672}\n:::\n:::\n\n\n## Map of unmatched facilities in FY25\n::: column-screen-inset-right\n\n::: {.cell}\n\n```{.r .cell-code}\nmap_data <- peak_fy25 |>\n  filter(peak_pop > 0, !is.na(latitude), !is.na(longitude))\n\nmap_sf <- st_as_sf(map_data, coords = c(\"longitude\", \"latitude\"), crs = 4326)\n\ntype_colors <- c(\n  \"Dedicated\"     = \"#e41a1c\",\n  \"Non-Dedicated\" = \"#377eb8\",\n  \"Federal\"       = \"#4daf4a\",\n  \"Hold/Staging\"  = \"#ff7f00\",\n  \"Family/Youth\"  = \"#984ea3\",\n  \"Medical\"       = \"#a65628\",\n  \"Other/Unknown\" = \"#999999\",\n  \"Unclassified\"  = \"#333333\"\n)\n\nmap_sf$type_grouped <- factor(map_sf$type_grouped, levels = names(type_colors))\npresent_levels <- levels(droplevels(map_sf$type_grouped))\npal <- colorFactor(palette = type_colors[present_levels], domain = present_levels)\n\n# sqrt scale for area-proportional circle sizing\nradii <- scales::rescale(sqrt(map_sf$peak_pop), to = c(3, 20))\n\nmap_sf$peak_class <- factor(map_sf$peak_class, levels = c(\"Peak < 2\", \"Peak ≥ 2\"))\n\nleaflet(map_sf) |>\n  fitBounds(lng1 = -125, lat1 = 17.5, lng2 = -65, lat2 = 49.5) |>\n  addProviderTiles(\"CartoDB.Positron\") |>\n\n  # Layer 1: Peak < 2  (small solid points, no border)\n  addCircleMarkers(\n    data        = subset(map_sf, peak_class == \"Peak < 2\"),\n    radius      = 3,                # small fixed dot\n    stroke      = FALSE,            # <- no outer border\n    fillColor   = ~pal(type_grouped),\n    fillOpacity = 1,                # solid\n    label       = ~paste0(detention_facility, \" (\", state, \": peak \", peak_pop, \")\"),\n    popup       = ~paste0(\n      \"<b>\", detention_facility, \"</b><br>\",\n      state, \" | \", type_grouped, \"<br>\",\n      \"Peak: \", peak_pop, \" (\", peak_date, \")<br>\",\n      \"Mean ADP: \", mean_pop\n    ),\n    group = \"Peak < 2\"\n  ) |>\n\n  # Layer 2: Peak ≥ 2\n  addCircleMarkers(\n    data        = subset(map_sf, peak_class == \"Peak ≥ 2\"),\n    radius      = radii[map_sf$peak_class == \"Peak ≥ 2\"],\n    color       = \"black\",\n    weight      = 1,\n    fillColor   = ~pal(type_grouped),\n    fillOpacity = 0.7,\n    label       = ~paste0(detention_facility, \" (\", state, \": peak \", peak_pop, \")\"),\n    popup       = ~paste0(\n      \"<b>\", detention_facility, \"</b><br>\",\n      state, \" | \", type_grouped, \"<br>\",\n      \"Peak: \", peak_pop, \" (\", peak_date, \")<br>\",\n      \"Mean ADP: \", mean_pop\n    ),\n    group = \"Peak ≥ 2\"\n  ) |>\n\n  # Keep your facility-type legend\n  addLegend(\n    pal = pal, values = ~type_grouped,\n    title = \"Facility type\", position = \"bottomright\"\n  ) |>\n\n  # Add the layer toggle\n  addLayersControl(\n    overlayGroups = c(\"Peak < 2\", \"Peak ≥ 2\"),\n    options = layersControlOptions(collapsed = FALSE)\n  ) |>\n  addSearchFeatures(\n    targetGroups = c(\"Peak < 2\", \"Peak ≥ 2\"),\n    options = searchFeaturesOptions(\n      zoom = 9,\n      openPopup = TRUE,\n      position = \"topleft\",\n      hideMarkerOnCollapse = TRUE\n    )) |>\n  addControl(\n    position = \"bottomright\",\n    html = htmltools::tags$style(htmltools::HTML(\"\n      /* Force legend text left in Quarto/Bootstrap contexts */\n      .leaflet-container .leaflet-control {\n        text-align: left !important;\n      }\n      .leaflet-container .leaflet-control .legend {\n        text-align: left !important;\n      }\n\n      /* Make the color swatch and label behave like a left-aligned row */\n      .leaflet-container .leaflet-control .legend i {\n        display: inline-block !important;\n        width: 14px !important;\n        height: 14px !important;\n        margin: 0 8px 0 0 !important;\n        vertical-align: middle !important;\n      }\n      .leaflet-container .leaflet-control .legend span {\n        display: inline !important;\n        vertical-align: middle !important;\n      }\n    \")))\n```\n\n::: {#fig-map .cell-output-display}\n\n```{=html}\n<div class=\"leaflet html-widget html-fill-item\" id=\"htmlwidget-4317ccb69be884af89a1\" style=\"width:100%;height:650px;\"></div>\n<script type=\"application/json\" data-for=\"htmlwidget-4317ccb69be884af89a1\">{\"x\":{\"options\":{\"crs\":{\"crsClass\":\"L.CRS.EPSG3857\",\"code\":null,\"proj4def\":null,\"projectedBounds\":null,\"options\":{}}},\"fitBounds\":[17.5,-125,49.5,-65,[]],\"calls\":[{\"method\":\"addProviderTiles\",\"args\":[\"CartoDB.Positron\",null,null,{\"errorTileUrl\":\"\",\"noWrap\":false,\"detectRetina\":false}]},{\"method\":\"addCircleMarkers\",\"args\":[[40.1917752,38.7981291,32.8420841,45.7836118,36.9886172,29.9542788,32.8460024,36.8682675,35.179783,43.0201451,34.4181788,32.3029629,39.3658822,42.596401,40.9242015,33.1771862,25.773994,29.4651997,26.0757281,40.6048678,32.3819047,35.6221933,31.85131,39.3714749,38.2754264,38.7519901,35.115385,41.509035,33.7482944,15.1567839,34.1023852,34.0265493,37.2165677,30.1967424,39.9865257],[-75.915868,-77.0646527,-97.13133500000001,-108.5095733,-86.48028640000001,-82.1085483,-80.01401620000001,-87.490437,-107.907649,-78.2023932,-85.7729963,-106.8056701,-77.41307570000001,-72.61253189999999,-98.3432364,-99.7217295,-80.195019,-82.6408105,-97.512372,-75.4664248,-86.29798959999999,-95.97454980000001,-92.28482,-94.78011720000001,-104.6106011,-77.4799665,-101.8680283,-90.58090900000001,-117.8744444,145.7028775,-117.2740451,-90.4462432,-76.60355729999999,-84.3771057,-76.6609023],3,null,\"Peak < 2\",{\"interactive\":true,\"className\":\"\",\"stroke\":false,\"color\":\"#03F\",\"weight\":5,\"opacity\":0.5,\"fill\":true,\"fillColor\":[\"#377EB8\",\"#4DAF4A\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#4DAF4A\",\"#A65628\",\"#FF7F00\",\"#4DAF4A\",\"#A65628\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#984EA3\",\"#A65628\",\"#A65628\",\"#A65628\",\"#A65628\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#A65628\",\"#FF7F00\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#A65628\",\"#A65628\"],\"fillOpacity\":1},null,null,[\"<b>ABRAXAS ACADEMY DETENTION CENTER<\\/b><br>PA | Family/Youth<br>Peak: 1 (2025-08-30)<br>Mean ADP: 0\",\"<b>ALEXANDRIA CITY JAIL<\\/b><br>VA | Federal<br>Peak: 1 (2025-05-21)<br>Mean ADP: 0\",\"<b>BEDFORD CITY JAIL<\\/b><br>TX | Non-Dedicated<br>Peak: 1 (2025-08-16)<br>Mean ADP: 0\",\"<b>BILLINGS HOLD ROOM<\\/b><br>MT | Hold/Staging<br>Peak: 1 (2025-06-21)<br>Mean ADP: 0\",\"<b>BOWLING GREEN HOLD ROOM<\\/b><br>KY | Hold/Staging<br>Peak: 1 (2024-10-09)<br>Mean ADP: 0\",\"<b>BRADFORD COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-01-14)<br>Mean ADP: 0\",\"<b>CHARLESTON COUNTY CORRECT<\\/b><br>SC | Federal<br>Peak: 1 (2025-03-15)<br>Mean ADP: 0\",\"<b>CHRISTIAN COUNTY JAIL<\\/b><br>KY | Federal<br>Peak: 1 (2025-09-18)<br>Mean ADP: 0\",\"<b>CIBOLA COUNTY DET CTR<\\/b><br>NM | Non-Dedicated<br>Peak: 1 (2025-05-11)<br>Mean ADP: 0\",\"<b>BATAVIA COMMAND CENTER HOLDROOM<\\/b><br>NY | Hold/Staging<br>Peak: 1 (2024-11-08)<br>Mean ADP: 0\",\"<b>DEKALB COUNTY DETENTION CENTER<\\/b><br>AL | Federal<br>Peak: 1 (2025-08-09)<br>Mean ADP: 0\",\"<b>DONA ANA COUNTY DETENTION FACILITY<\\/b><br>NM | Non-Dedicated<br>Peak: 1 (2025-04-24)<br>Mean ADP: 0.4\",\"<b>FREDERICK COUNTY DET. CEN<\\/b><br>MD | Non-Dedicated<br>Peak: 1 (2024-11-30)<br>Mean ADP: 0\",\"<b>FRANKLIN HOUSE OF CORRECTIONS<\\/b><br>MA | Federal<br>Peak: 1 (2025-08-09)<br>Mean ADP: 0\",\"<b>GRAND ISLAND HOLD ROOM<\\/b><br>NE | Hold/Staging<br>Peak: 1 (2025-06-25)<br>Mean ADP: 0\",\"<b>ROLLING PLAINS DETENTION CENTER<\\/b><br>TX | Federal<br>Peak: 1 (2024-11-21)<br>Mean ADP: 0\",\"<b>MIAMI BORDER PATROL<\\/b><br>FL | Hold/Staging<br>Peak: 1 (2025-07-02)<br>Mean ADP: 0\",\"<b>LEVY COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2024-12-03)<br>Mean ADP: 0\",\"<b>LOS FRESNOS HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 1 (2024-11-11)<br>Mean ADP: 0\",\"<b>LEHIGH VALLEY HOSPITAL - POCONO<\\/b><br>PA | Medical<br>Peak: 1 (2024-10-01)<br>Mean ADP: 0\",\"<b>MONTGOMERY CITY JAIL<\\/b><br>AL | Non-Dedicated<br>Peak: 1 (2025-01-07)<br>Mean ADP: 0\",\"<b>OKMULGEE COUNTY JAIL<\\/b><br>OK | Non-Dedicated<br>Peak: 1 (2025-09-23)<br>Mean ADP: 0\",\"<b>LASALLE CORR CTR OLLA<\\/b><br>LA | Non-Dedicated<br>Peak: 1 (2025-02-22)<br>Mean ADP: 0\",\"<b>PLATTE COUNTY JAIL<\\/b><br>MO | Non-Dedicated<br>Peak: 1 (2025-03-07)<br>Mean ADP: 0\",\"<b>PUEBLO COUNTY JAIL<\\/b><br>CO | Federal<br>Peak: 1 (2025-05-14)<br>Mean ADP: 0\",\"<b>PRINCE WILLIAM<\\/b><br>VA | Federal<br>Peak: 1 (2025-01-04)<br>Mean ADP: 0\",\"<b>RANDALL COUNTY JAIL<\\/b><br>TX | Federal<br>Peak: 1 (2025-04-26)<br>Mean ADP: 0\",\"<b>ROCK ISLAND COUNTY JAIL<\\/b><br>IL | Federal<br>Peak: 1 (2025-08-15)<br>Mean ADP: 0\",\"<b>SANTA ANA CITY JAIL<\\/b><br>CA | Non-Dedicated<br>Peak: 1 (2025-05-08)<br>Mean ADP: 0\",\"<b>SAIPAIN HOLD<\\/b><br>MP | Hold/Staging<br>Peak: 1 (2024-11-15)<br>Mean ADP: 0\",\"<b>SAN BERNARDINO CO. JAIL<\\/b><br>CA | Federal<br>Peak: 1 (2025-08-09)<br>Mean ADP: 0\",\"<b>TALLAHATCHIE CO CORR FACILITY<\\/b><br>MS | Federal<br>Peak: 1 (2025-05-07)<br>Mean ADP: 0\",\"<b>VIRGINIA PENINSULA REG. JAIL<\\/b><br>VA | Federal<br>Peak: 1 (2025-07-11)<br>Mean ADP: 0\",\"<b>WAKULLA COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 1 (2025-05-07)<br>Mean ADP: 0\",\"<b>YORK COUNTY JAIL, PA<\\/b><br>PA | Non-Dedicated<br>Peak: 1 (2024-10-01)<br>Mean ADP: 1\"],null,[\"ABRAXAS ACADEMY DETENTION CENTER (PA: peak 1)\",\"ALEXANDRIA CITY JAIL (VA: peak 1)\",\"BEDFORD CITY JAIL (TX: peak 1)\",\"BILLINGS HOLD ROOM (MT: peak 1)\",\"BOWLING GREEN HOLD ROOM (KY: peak 1)\",\"BRADFORD COUNTY JAIL (FL: peak 1)\",\"CHARLESTON COUNTY CORRECT (SC: peak 1)\",\"CHRISTIAN COUNTY JAIL (KY: peak 1)\",\"CIBOLA COUNTY DET CTR (NM: peak 1)\",\"BATAVIA COMMAND CENTER HOLDROOM (NY: peak 1)\",\"DEKALB COUNTY DETENTION CENTER (AL: peak 1)\",\"DONA ANA COUNTY DETENTION FACILITY (NM: peak 1)\",\"FREDERICK COUNTY DET. CEN (MD: peak 1)\",\"FRANKLIN HOUSE OF CORRECTIONS (MA: peak 1)\",\"GRAND ISLAND HOLD ROOM (NE: peak 1)\",\"ROLLING PLAINS DETENTION CENTER (TX: peak 1)\",\"MIAMI BORDER PATROL (FL: peak 1)\",\"LEVY COUNTY JAIL (FL: peak 1)\",\"LOS FRESNOS HOLD ROOM (TX: peak 1)\",\"LEHIGH VALLEY HOSPITAL - POCONO (PA: peak 1)\",\"MONTGOMERY CITY JAIL (AL: peak 1)\",\"OKMULGEE COUNTY JAIL (OK: peak 1)\",\"LASALLE CORR CTR OLLA (LA: peak 1)\",\"PLATTE COUNTY JAIL (MO: peak 1)\",\"PUEBLO COUNTY JAIL (CO: peak 1)\",\"PRINCE WILLIAM (VA: peak 1)\",\"RANDALL COUNTY JAIL (TX: peak 1)\",\"ROCK ISLAND COUNTY JAIL (IL: peak 1)\",\"SANTA ANA CITY JAIL (CA: peak 1)\",\"SAIPAIN HOLD (MP: peak 1)\",\"SAN BERNARDINO CO. JAIL (CA: peak 1)\",\"TALLAHATCHIE CO CORR FACILITY (MS: peak 1)\",\"VIRGINIA PENINSULA REG. JAIL (VA: peak 1)\",\"WAKULLA COUNTY JAIL (FL: peak 1)\",\"YORK COUNTY JAIL, PA (PA: peak 1)\"],{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},null]},{\"method\":\"addCircleMarkers\",\"args\":[[35.0522552,13.4760946,18.4962828,42.7653031,37.4893878,35.115385,61.2185041,61.212362,33.7475641,33.749609,32.2035715,30.2693858,33.452963,30.8852959,39.2879833,33.4792816,35.3736714,43.5942506,18.4235781,42.4825992,26.1161559,27.2482081,41.8680102,32.2248668,42.8911691,41.7351513,47.466362,42.8911691,35.4090546,18.3403438,33.3515168,41.87539049999999,32.8463863,45.0068737,41.1368016,39.2382289,40.7594706,41.5049609,39.9624569,35.2226924,35.1059466,34.0088782,33.9084065,40.5136142,41.9745858,27.7795664,38.8332903,42.8523725,32.8238894,39.6015038,42.3310002,29.3927093,33.057249,41.5856411,37.2371432,39.1536338,31.7584731,31.80421399999999,31.883642,34.015507,44.0524622,36.10463,48.82974489999999,37.9676572,30.214814,25.86434,26.548482,40.001549,40.08207549999999,36.7326978,35.3354817,34.7404942,35.257809,39.0871873,34.1473511,47.924267,42.97265429999999,34.9393051,39.5582742,43.665091,41.7613805,38.4271142,46.5937137,35.3187546,21.2999288,27.959392,26.1776479,29.9375017,43.5147311,32.8266637,39.7659792,33.4183833,32.2902501,30.2566701,31.549304,39.2686641,28.8837901,28.884651,35.9232411,25.75434,25.7581461,41.1347715,32.3473177,44.3742947,33.5841136,38.9718009,34.053793,38.2531573,34.7211076,27.5292214,36.1641801,42.9984836,27.1719467,26.2639943,42.3255106,35.1563308,25.9827432,31.994141,43.0471532,42.5350478,31.994141,39.93274359999999,30.695111,24.576552,32.3743852,25.7783254,30.3360804,41.5157485,40.7304926,29.9857549,36.87616999999999,41.1345586,36.2251232,40.7152635,36.2206495,30.8310871,41.2205835,35.4236398,41.2820726,28.4281216,31.3981762,31.75103519999999,39.9538838,33.4708461,40.4248324,41.3885184,42.05559290000001,43.5788489,45.51504569999999,32.42078539,41.7357562,40.1488668,38.4265663,37.5429144,35.7897748,40.5749834,39.5711833,26.1569011,46.27814770000001,41.509035,37.2923927,37.2711908,44.1007278,33.3980667,33.7484501,38.57800230000001,31.4215029,18.4078569,38.4105074,40.481929,34.1006917,47.4907997,43.5499676,37.7962167,37.1197342,43.0185162,18.437531,40.7062912,34.918106,29.517042,32.7143776,37.3080994,37.2518247,44.8941668,47.66582,44.8014691,28.8973835,37.9512028,38.6243789,27.1628237,42.505249,43.0468521,30.4719963,27.959392,38.943053,42.5625826,25.8101315,31.4635264,32.586731,33.1546792,35.4074582,32.1356653,36.139538,33.4208569,29.373265,34.2063593,40.7282753,32.5136216,38.9114848,31.5532338,33.7531536,37.6912501,46.6183336,41.2239063,39.4373784,46.6183336,39.9849944,32.6565319],[-106.6270349,144.750006,-67.1355075,-73.8121646,-105.8597721,-101.8680283,-149.8573539,-149.8722992,-84.3955253,-84.39734609999999,-95.8558275,-97.73903919999999,-112.025979,-87.774794,-76.616563,-86.7899669,-119.0112192,-116.2875233,-66.1036671,-71.20881349999999,-80.1424222,-98.1249164,-87.8659385,-101.5140425,-78.8769453,-111.8361612,-111.380434,-78.8769453,-80.5782942,-64.9265683,-104.5043043,-87.6309402,-80.0199001,-73.4558729,-104.8198764,-84.380236,-73.1909642,-81.69177239999999,-83.0021146,-80.83722440000001,-85.29861769999999,-81.0401775,-84.5809412,-107.5451612,-91.6691514,-97.54361230000001,-104.8172348,-106.3242133,-96.8720089,-104.8449885,-83.05871789999999,-100.8988898,-80.221052,-93.62360080000001,-107.874248,-75.4882617,-106.4831939,-106.2910235,-106.440946,-86.01235659999999,-123.0885813,-94.178449,-122.5553748,-100.8759294,-82.372328,-80.89795599999999,-81.8109453,-77.64440999999999,-104.9849103,-119.7856018,-94.38919970000001,-97.2220938,-81.1822263,-108.5858668,-118.2491447,-97.0353236,-85.67052609999999,-82.24697139999999,-107.3582581,-116.6817811,-72.6734969,-78.8495901,-111.9724396,-82.467828,-157.8638944,-82.37207239999999,-97.714091,-95.40658999999999,-112.0339375,-115.5793027,-86.15315729999999,-111.8375752,-90.05970979999999,-81.5900041,-97.081435,-94.6755746,-97.9119663,-97.91529800000001,-84.07938129999999,-80.48913,-80.35093879999999,-104.8201135,-106.7626739,-103.7295749,-101.8450548,-90.96271609999999,-118.2397435,-85.76081689999999,-92.2249691,-99.447934,-115.1435135,-71.46629639999999,-80.24193769999999,-98.1982091,-122.8772236,-89.88122030000001,-80.33946019999999,-102.0750416,-87.9080261,-113.7911723,-102.0750416,-74.9576161,-88.041554,-81.75143799999999,-86.30494399999999,-80.1990136,-95.4425066,-74.1110231,-74.17423119999999,-90.2854711,-76.22287609999999,-100.7607001,-86.7865862,-74.00375459999999,-115.9869885,-92.65038920000001,-112.0191482,-97.59751919999999,-95.8987599,-81.3331197,-103.5214509,-106.4868749,-75.15313019999999,-112.0731981,-79.96081099999999,-75.0724974,-104.9522605,-70.3604263,-122.67631,-97.19690233999999,-71.4411413,-111.6597178,-105.1156314,-77.43404769999999,-78.77960730000001,-122.3626062,-119.8111143,-97.35055610000001,-119.2763319,-90.58090900000001,-80.06114029999999,-79.9471628,-103.2667352,-104.5248121,-117.8749858,-121.4999684,-100.4638024,-66.1074296,-75.571609,-96.9608662,-117.2972977,-122.2914497,-96.7233919,-122.401521,-113.5534693,-96.07665849999999,-66.00470300000001,-111.9461895,-120.444791,-98.4366327,-117.1645829,-121.8675044,-93.1678639,-93.1948264,-117.4181833,-73.0734028,-99.1187908,-121.2900671,-90.2003828,-80.221999,-96.4047597,-76.1516563,-84.35514119999999,-82.37207239999999,-105.1513323,-114.4338469,-80.3113644,-100.4398316,-97.3168944,-94.97105120000001,-89.54861219999999,-110.9248046,-95.86430900000001,-94.0431833,-100.847867,-119.0772538,-74.00556619999999,-93.74924059999999,-77.45867679999999,-97.1334651,-118.0010421,-97.3396394,-120.5593593,-77.0718055,-77.96108959999999,-120.5593593,-76.7579657,-114.6117867],[5.483420118779979,3.435061561946088,5.934910806038285,4.305184685838265,3.716003135966583,4.358743211603835,5.417827884802192,3.537765664962601,3.318487167764811,8.203980779687726,4.192789745010902,5.579133356897509,3.318487167764811,4.867067833879256,7.330799065679987,4.410748322168053,5.61036937167653,3.795478360796673,4.305184685838265,8.80924655927053,4.192789745010902,6.692294812474142,9.374729026414737,3.940723896193989,5.483420118779979,4.133575207633986,3.537765664962601,4.510592891871291,3.630617271520083,3.435061561946088,4.305184685838265,3.716003135966583,6.1788311903537,3.795478360796673,3.318487167764811,3.435061561946088,5.483420118779979,4.192789745010902,3.940723896193989,5.579133356897509,4.07203589747571,4.987258698294508,3.435061561946088,3.435061561946088,4.358743211603835,3.795478360796673,3.716003135966583,3.630617271520083,9.090861867245238,5.138797349086906,5.547570236667276,4.07203589747571,3.940723896193989,3.318487167764811,3.630617271520083,3.940723896193989,6.8053940096738,3.180208399425292,20,3.180208399425292,3.870123123892177,3.870123123892177,3.630617271520083,4.00787439973505,3.716003135966583,19.31339597587397,4.907816650382954,3.180208399425292,3.716003135966583,4.605558044699242,3.435061561946088,4.249924622046098,3.630617271520083,3.716003135966583,4.605558044699242,4.133575207633986,3.870123123892177,3.716003135966583,3.940723896193989,3.180208399425292,5.211314605432596,4.00787439973505,3.180208399425292,3.537765664962601,3.435061561946088,5.316509354334065,7.290916685632974,4.410748322168053,3.537765664962601,4.07203589747571,7.525403451415674,8.64024252288614,4.651420391416631,5.138797349086906,3.630617271520083,6.045430933622619,3.940723896193989,3.870123123892177,4.510592891871291,5.761974938452427,13.22172677271563,3.795478360796673,3.716003135966583,3.537765664962601,4.358743211603835,3.435061561946088,11.84511871759328,4.651420391416631,4.82558462718661,7.230453919599499,6.152547985153758,3.870123123892177,4.696296104986255,5.906709704657183,4.192789745010902,4.740246247784354,6.78301677921819,4.133575207633986,4.605558044699242,3.795478360796673,4.133575207633986,4.783325832031172,5.138797349086906,3.318487167764811,3.180208399425292,8.336682284778464,9.03259352726023,3.940723896193989,4.07203589747571,3.537765664962601,4.305184685838265,4.133575207633986,6.332682086608409,9.134223961740425,6.692294812474142,4.192789745010902,4.133575207633986,6.431850184131735,6.282106052764985,7.448492358924882,4.867067833879256,5.175307809730442,5.064176835753901,6.692294812474142,4.461327820795872,3.716003135966583,4.00787439973505,3.318487167764811,4.461327820795872,6.480492495568707,3.795478360796673,3.940723896193989,4.249924622046098,9.805805918071947,4.192789745010902,3.716003135966583,3.940723896193989,4.55864097763758,3.435061561946088,3.630617271520083,3.630617271520083,4.133575207633986,3.716003135966583,4.305184685838265,7.89333260538477,5.138797349086906,4.510592891871291,5.641288244910815,4.651420391416631,3.716003135966583,5.246838022667934,5.906709704657183,4.510592891871291,5.450810361416188,3.870123123892177,3.940723896193989,4.696296104986255,5.579133356897509,4.461327820795872,7.803773383824837,6.152547985153758,3.180208399425292,5.990616602497289,6.622922537753959,4.358743211603835,3.716003135966583,5.671899444701964,4.192789745010902,5.175307809730442,5.732234417623458,3.318487167764811,4.192789745010902,5.483420118779979,6.552343517221249,3.180208399425292,3.630617271520083,4.82558462718661,4.249924622046098,3.435061561946088,3.630617271520083,5.281897021587314,4.249924622046098,4.305184685838265,3.630617271520083,5.138797349086906,6.456247345688668,4.07203589747571,3.795478360796673,7.467833242221873,4.696296104986255,3.795478360796673,3.180208399425292,3.435061561946088,4.55864097763758,4.305184685838265,4.07203589747571,4.305184685838265,3.795478360796673],null,\"Peak ≥ 2\",{\"interactive\":true,\"className\":\"\",\"stroke\":true,\"color\":\"black\",\"weight\":1,\"opacity\":0.5,\"fill\":true,\"fillColor\":[\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#4DAF4A\",\"#4DAF4A\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#333333\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#E41A1C\",\"#E41A1C\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#4DAF4A\",\"#377EB8\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#A65628\",\"#FF7F00\",\"#A65628\",\"#4DAF4A\",\"#984EA3\",\"#4DAF4A\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\",\"#4DAF4A\",\"#FF7F00\",\"#FF7F00\",\"#FF7F00\"],\"fillOpacity\":0.7},null,null,[\"<b>ALBUQUERQUE HOLD ROOM<\\/b><br>NM | Hold/Staging<br>Peak: 45 (2025-03-25)<br>Mean ADP: 2\",\"<b>GUAM ERO HOLD ROOM<\\/b><br>GU | Hold/Staging<br>Peak: 4 (2025-05-22)<br>Mean ADP: 0\",\"<b>AGUADILLA SPC<\\/b><br>PR | Hold/Staging<br>Peak: 60 (2025-03-20)<br>Mean ADP: 3.3\",\"<b>ALBANY HOLDROOM<\\/b><br>NY | Hold/Staging<br>Peak: 16 (2025-07-15)<br>Mean ADP: 1.2\",\"<b>ALAMOSA HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 7 (2025-08-19)<br>Mean ADP: 0.2\",\"<b>AMARILLO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 17 (2025-09-03)<br>Mean ADP: 2.1\",\"<b>ANCHORAGE JAIL<\\/b><br>AK | Federal<br>Peak: 43 (2025-06-09)<br>Mean ADP: 3.3\",\"<b>ANCHORAGE SUB-OFFICE HOLD ROOM<\\/b><br>AK | Hold/Staging<br>Peak: 5 (2025-09-12)<br>Mean ADP: 0\",\"<b>ATLANTA PRETRIAL DETN CTR<\\/b><br>GA | Federal<br>Peak: 3 (2025-04-27)<br>Mean ADP: 0\",\"<b>ATLANTA DIST. HOLD RM<\\/b><br>GA | Hold/Staging<br>Peak: 168 (2025-06-25)<br>Mean ADP: 42.1\",\"<b>ATHENS, TX HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 14 (2025-09-23)<br>Mean ADP: 0.1\",\"<b>AUSTIN DRO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 48 (2025-09-17)<br>Mean ADP: 15.2\",\"<b>ARIZONA STATE PRISON - YUMA<\\/b><br>AZ | Non-Dedicated<br>Peak: 3 (2025-04-03)<br>Mean ADP: 0\",\"<b>BALDWIN COUNTY COR. CENTER<\\/b><br>AL | Non-Dedicated<br>Peak: 28 (2025-02-07)<br>Mean ADP: 1.4\",\"<b>BALTIMORE HOLD ROOM<\\/b><br>MD | Hold/Staging<br>Peak: 120 (2025-06-13)<br>Mean ADP: 29.3\",\"<b>BIRMINGHAM HOLD ROOM<\\/b><br>AL | Hold/Staging<br>Peak: 18 (2025-09-10)<br>Mean ADP: 1.2\",\"<b>BAKERFIELD HOLD<\\/b><br>CA | Hold/Staging<br>Peak: 49 (2025-04-30)<br>Mean ADP: 7.1\",\"<b>BOISE HOLD ROOM<\\/b><br>ID | Hold/Staging<br>Peak: 8 (2025-06-04)<br>Mean ADP: 0.8\",\"<b>GUAYNABO MDC (SAN JUAN)<\\/b><br>PR | Federal<br>Peak: 16 (2024-10-01)<br>Mean ADP: 2.8\",\"<b>BOSTON HOLDROOM<\\/b><br>MA | Hold/Staging<br>Peak: 206 (2025-05-13)<br>Mean ADP: 18.6\",\"<b>BROWARD COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 14 (2025-07-26)<br>Mean ADP: 3.4\",\"<b>BROOKS COUNTY JAIL (CONTRACT)<\\/b><br>TX | Federal<br>Peak: 90 (2025-08-19)<br>Mean ADP: 4.5\",\"<b>BROADVIEW SERVICE STAGING<\\/b><br>IL | Hold/Staging<br>Peak: 245 (2025-09-20)<br>Mean ADP: 31.7\",\"<b>BIG SPRING HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 10 (2025-04-11)<br>Mean ADP: 0.9\",\"<b>BUFFALO HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 45 (2025-06-16)<br>Mean ADP: 1.6\",\"<b>CACHE CO. JAIL<\\/b><br>UT | Federal<br>Peak: 13 (2025-09-19)<br>Mean ADP: 0.3\",\"<b>CASCADE COUNTY JAIL, MT<\\/b><br>MT | Federal<br>Peak: 5 (2025-08-03)<br>Mean ADP: 0.7\",\"<b>BUFFALO USBP HOLD ROOM<\\/b><br>NY | Federal<br>Peak: 20 (2025-09-17)<br>Mean ADP: 0.2\",\"<b>Cabarrus County Jail<\\/b><br>NC | Non-Dedicated<br>Peak: 6 (2025-07-31)<br>Mean ADP: 0.7\",\"<b>CHARLOTTE AMALIE HOLDROOM<\\/b><br>VI | Hold/Staging<br>Peak: 4 (2025-01-24)<br>Mean ADP: 0.2\",\"<b>CHAVEZ DET CRT<\\/b><br>NM | Non-Dedicated<br>Peak: 16 (2025-09-17)<br>Mean ADP: 2.1\",\"<b>CHICAGO HOLD ROOM<\\/b><br>IL | Hold/Staging<br>Peak: 7 (2025-09-21)<br>Mean ADP: 0.3\",\"<b>CHARLESTON, SC HOLD ROOM<\\/b><br>SC | Hold/Staging<br>Peak: 69 (2025-06-01)<br>Mean ADP: 8.7\",\"<b>CHAMPLAIN HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 8 (2025-09-18)<br>Mean ADP: 0.2\",\"<b>CHEYENNE HOLDROOM<\\/b><br>WY | Hold/Staging<br>Peak: 3 (2025-01-27)<br>Mean ADP: 0.3\",\"<b>CINCINNATI HOLDROOM<\\/b><br>OH | Hold/Staging<br>Peak: 4 (2025-02-04)<br>Mean ADP: 0\",\"<b>CENTRAL ISLIP HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 45 (2025-06-05)<br>Mean ADP: 3\",\"<b>CLEVELAND HOLD ROOM<\\/b><br>OH | Hold/Staging<br>Peak: 14 (2025-06-04)<br>Mean ADP: 0.3\",\"<b>COLUMBUS HOLDROOM<\\/b><br>OH | Hold/Staging<br>Peak: 10 (2025-03-04)<br>Mean ADP: 0.4\",\"<b>CHARLOTTE HOLD ROOM<\\/b><br>NC | Hold/Staging<br>Peak: 48 (2025-06-29)<br>Mean ADP: 9.7\",\"<b>CHATTANOOGA HOLD ROOM<\\/b><br>TN | Hold/Staging<br>Peak: 12 (2025-07-03)<br>Mean ADP: 2.5\",\"<b>COLUMBIA, SC HOLDROOM<\\/b><br>SC | Hold/Staging<br>Peak: 31 (2025-03-12)<br>Mean ADP: 1.3\",\"<b>COBB CO SHERIFFS OFC ADULT DET CTR<\\/b><br>GA | Non-Dedicated<br>Peak: 4 (2024-12-13)<br>Mean ADP: 0.3\",\"<b>CRAIG HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 4 (2025-09-23)<br>Mean ADP: 0.2\",\"<b>CEDAR RAPIDS HOLD ROOM<\\/b><br>IA | Hold/Staging<br>Peak: 17 (2025-08-23)<br>Mean ADP: 0.7\",\"<b>CORPUS CHRISTI EOR HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 8 (2025-09-09)<br>Mean ADP: 0.8\",\"<b>COLO SPRINGS DEN HSI HOLD<\\/b><br>CO | Hold/Staging<br>Peak: 7 (2025-08-22)<br>Mean ADP: 0.4\",\"<b>CASPER HOLDROOM<\\/b><br>WY | Hold/Staging<br>Peak: 6 (2025-03-14)<br>Mean ADP: 0.5\",\"<b>DALLAS F.O. HOLD<\\/b><br>TX | Hold/Staging<br>Peak: 225 (2025-09-18)<br>Mean ADP: 53.1\",\"<b>DENVER HOLD ROOM<\\/b><br>CO | Hold/Staging<br>Peak: 35 (2025-04-28)<br>Mean ADP: 5\",\"<b>DETROIT HOLDROOM<\\/b><br>MI | Hold/Staging<br>Peak: 47 (2025-06-19)<br>Mean ADP: 1.2\",\"<b>DEL RIO DRO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 12 (2025-09-06)<br>Mean ADP: 1\",\"<b>DORCHESTER CO DET CTR<\\/b><br>SC | Federal<br>Peak: 10 (2025-09-14)<br>Mean ADP: 1.3\",\"<b>DES MOINES HOLD ROOM<\\/b><br>IA | Hold/Staging<br>Peak: 3 (2025-04-19)<br>Mean ADP: 0.3\",\"<b>DURANGO HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 6 (2025-08-18)<br>Mean ADP: 0.1\",\"<b>DOVER HOLDROOM<\\/b><br>DE | Hold/Staging<br>Peak: 10 (2025-06-12)<br>Mean ADP: 1.4\",\"<b>EL PASO COUNTY DETENTION FACILITY<\\/b><br>TX | Non-Dedicated<br>Peak: 95 (2024-12-30)<br>Mean ADP: 1.4\",\"<b>EGP CPC HOLDING<\\/b><br>TX | Unclassified<br>Peak: 2 (2025-04-17)<br>Mean ADP: 0\",\"<b>EL PASO SOFT SIDED FACILITY<\\/b><br>TX | Hold/Staging<br>Peak: 1606 (2025-08-12)<br>Mean ADP: 243.2\",\"<b>ETOWAH ERO HOLD ROOM<\\/b><br>AL | Hold/Staging<br>Peak: 2 (2024-10-15)<br>Mean ADP: 0\",\"<b>EUGENE HOLDROOM<\\/b><br>OR | Hold/Staging<br>Peak: 9 (2025-01-27)<br>Mean ADP: 0.4\",\"<b>FAYETTEVILLE HOLD ROOM<\\/b><br>AR | Hold/Staging<br>Peak: 9 (2025-03-05)<br>Mean ADP: 0.3\",\"<b>FERNDALE HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 6 (2025-06-10)<br>Mean ADP: 0.5\",\"<b>FINNEY COUNTY JAIL<\\/b><br>KS | Non-Dedicated<br>Peak: 11 (2025-02-26)<br>Mean ADP: 1.9\",\"<b>DADE CORRECTIONAL INST<\\/b><br>FL | Dedicated<br>Peak: 7 (2025-08-25)<br>Mean ADP: 0.2\",\"<b>FLORIDA SOFT-SIDED FACILITY-SOUTH<\\/b><br>FL | Dedicated<br>Peak: 1482 (2025-07-30)<br>Mean ADP: 170.3\",\"<b>FORT MYERS ERO HOLDROOM<\\/b><br>FL | Hold/Staging<br>Peak: 29 (2025-06-21)<br>Mean ADP: 5\",\"<b>FRANKLIN COUNTY JAIL<\\/b><br>PA | Federal<br>Peak: 2 (2025-06-20)<br>Mean ADP: 0.1\",\"<b>FREDERICK HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 7 (2025-07-29)<br>Mean ADP: 1.3\",\"<b>FRESNO HOLDROOM<\\/b><br>CA | Hold/Staging<br>Peak: 22 (2025-08-29)<br>Mean ADP: 4.9\",\"<b>FORT SMITH HOLDROOM<\\/b><br>AR | Hold/Staging<br>Peak: 4 (2025-02-25)<br>Mean ADP: 0.1\",\"<b>GARVIN COUNTY JAIL<\\/b><br>OK | Non-Dedicated<br>Peak: 15 (2025-09-15)<br>Mean ADP: 0.6\",\"<b>GASTON COUNTY JAIL<\\/b><br>NC | Non-Dedicated<br>Peak: 6 (2025-03-19)<br>Mean ADP: 0.6\",\"<b>GRAND JUNCTION HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 7 (2025-06-03)<br>Mean ADP: 0.7\",\"<b>GLENDALE POLICE DEPT<\\/b><br>CA | Non-Dedicated<br>Peak: 22 (2025-06-03)<br>Mean ADP: 0.8\",\"<b>GRAND FORKS HOLD ROOM<\\/b><br>ND | Hold/Staging<br>Peak: 13 (2025-07-08)<br>Mean ADP: 0.5\",\"<b>GRAND RAPIDS HOLDROOM<\\/b><br>MI | Hold/Staging<br>Peak: 9 (2025-06-24)<br>Mean ADP: 0.8\",\"<b>GREER HOLD ROOM<\\/b><br>SC | Hold/Staging<br>Peak: 7 (2025-06-25)<br>Mean ADP: 1\",\"<b>GLENWOOD SPRINGS HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 10 (2025-05-22)<br>Mean ADP: 0.2\",\"<b>HAILE DET. CENTER<\\/b><br>ID | Non-Dedicated<br>Peak: 2 (2025-03-03)<br>Mean ADP: 0.1\",\"<b>HARTFORD OFFICE<\\/b><br>CT | Hold/Staging<br>Peak: 37 (2025-05-29)<br>Mean ADP: 4.6\",\"<b>HARRISONBURG HOLD ROOM<\\/b><br>VA | Hold/Staging<br>Peak: 11 (2025-06-03)<br>Mean ADP: 1.1\",\"<b>HEL DISTRICT CUSTODY<\\/b><br>MT | Hold/Staging<br>Peak: 2 (2025-08-19)<br>Mean ADP: 0\",\"<b>HENDERSONVILLE HOLD ROOM<\\/b><br>NC | Hold/Staging<br>Peak: 5 (2025-05-29)<br>Mean ADP: 0.1\",\"<b>ERO HONOLULU SUB-OFFICE HOLD ROOM<\\/b><br>HI | Hold/Staging<br>Peak: 4 (2025-03-06)<br>Mean ADP: 0.1\",\"<b>HILLSBOROUGH COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 40 (2025-07-03)<br>Mean ADP: 0.5\",\"<b>HARLINGEN HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 118 (2025-06-04)<br>Mean ADP: 15.4\",\"<b>HOUSTON FO HOLDROOM<\\/b><br>TX | Hold/Staging<br>Peak: 18 (2024-12-10)<br>Mean ADP: 1.7\",\"<b>IDAHO FALLS HOLD ROOM<\\/b><br>ID | Hold/Staging<br>Peak: 5 (2025-04-03)<br>Mean ADP: 0.2\",\"<b>IMPERIAL SUB OFFICE HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 12 (2025-09-03)<br>Mean ADP: 1.2\",\"<b>INDIANAPOLIS HOLD ROOM<\\/b><br>IN | Hold/Staging<br>Peak: 130 (2025-09-19)<br>Mean ADP: 12.3\",\"<b>AZ REM OP COORD CENTER (AROCC)<\\/b><br>AZ | Hold/Staging<br>Peak: 195 (2025-04-30)<br>Mean ADP: 37.4\",\"<b>JACKSON MS HOLD ROOM<\\/b><br>MS | Hold/Staging<br>Peak: 23 (2025-08-29)<br>Mean ADP: 4.2\",\"<b>JACKSONVILLE SUB-OFFICE<\\/b><br>FL | Hold/Staging<br>Peak: 35 (2025-04-25)<br>Mean ADP: 5.4\",\"<b>JACK HARWELL DETENTION CENTER<\\/b><br>TX | Federal<br>Peak: 6 (2025-05-15)<br>Mean ADP: 0.3\",\"<b>KANSAS CITY HOLDROOM<\\/b><br>MO | Hold/Staging<br>Peak: 64 (2025-05-09)<br>Mean ADP: 6.1\",\"<b>KARNES CTY CORR CTR<\\/b><br>TX | Federal<br>Peak: 10 (2025-02-25)<br>Mean ADP: 1.5\",\"<b>KARNES COUNTY CIVIL DET. FACILITY<\\/b><br>TX | Family/Youth<br>Peak: 9 (2025-04-23)<br>Mean ADP: 0.3\",\"<b>KNOXVILLE HOLD ROOM<\\/b><br>TN | Hold/Staging<br>Peak: 20 (2025-08-22)<br>Mean ADP: 3.3\",\"<b>KROME/MIAMI HUB<\\/b><br>FL | Hold/Staging<br>Peak: 54 (2025-05-24)<br>Mean ADP: 5.8\",\"<b>KROME HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 600 (2025-02-17)<br>Mean ADP: 36.5\",\"<b>LARAMIE COUNTY JAIL<\\/b><br>WY | Federal<br>Peak: 8 (2025-09-13)<br>Mean ADP: 0.2\",\"<b>LAS CRUCES HOLD ROOM<\\/b><br>NM | Hold/Staging<br>Peak: 7 (2025-08-05)<br>Mean ADP: 0.4\",\"<b>LAWRENCE CO. JAIL, SD<\\/b><br>SD | Non-Dedicated<br>Peak: 5 (2025-09-24)<br>Mean ADP: 0.2\",\"<b>LUBBOCK HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 17 (2025-09-10)<br>Mean ADP: 2.5\",\"<b>LINCOLN COUNTY SHERIFF'S<\\/b><br>MO | Non-Dedicated<br>Peak: 4 (2024-10-05)<br>Mean ADP: 0.3\",\"<b>LOS CUST CASE<\\/b><br>CA | Hold/Staging<br>Peak: 455 (2025-07-11)<br>Mean ADP: 58.7\",\"<b>LOUISVILLE HOLD ROOM<\\/b><br>KY | Hold/Staging<br>Peak: 23 (2025-03-12)<br>Mean ADP: 0.6\",\"<b>LITTLE ROCK HOLD ROOM<\\/b><br>AR | Hold/Staging<br>Peak: 27 (2025-02-25)<br>Mean ADP: 4.2\",\"<b>LAREDO DETENTION CENTER HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 115 (2024-12-31)<br>Mean ADP: 3.8\",\"<b>LAS VEGAS HOLD ROOM<\\/b><br>NV | Hold/Staging<br>Peak: 68 (2025-04-18)<br>Mean ADP: 4.2\",\"<b>MANCHESTER HOLDROOM<\\/b><br>NH | Hold/Staging<br>Peak: 9 (2025-02-18)<br>Mean ADP: 0.5\",\"<b>MARTIN COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 24 (2025-09-05)<br>Mean ADP: 1.5\",\"<b>MCALLEN HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 59 (2025-02-26)<br>Mean ADP: 9.7\",\"<b>MEDFORD SUB-OFFICE<\\/b><br>OR | Hold/Staging<br>Peak: 14 (2025-07-30)<br>Mean ADP: 0.2\",\"<b>MEMPHIS HOLD ROOM<\\/b><br>TN | Hold/Staging<br>Peak: 25 (2025-08-15)<br>Mean ADP: 5.2\",\"<b>MIAMI (MIRAMAR) HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 94 (2025-09-10)<br>Mean ADP: 12.6\",\"<b>MIDLAND DETENTION CENTER<\\/b><br>TX | Federal<br>Peak: 13 (2025-05-26)<br>Mean ADP: 1.1\",\"<b>MILWAUKEE HOLDROOM<\\/b><br>WI | Hold/Staging<br>Peak: 22 (2025-06-03)<br>Mean ADP: 1.4\",\"<b>MINICASSIA DET. CENTER<\\/b><br>ID | Non-Dedicated<br>Peak: 8 (2025-06-25)<br>Mean ADP: 0.7\",\"<b>MIDLAND, TX ERO HOLDROOM<\\/b><br>TX | Hold/Staging<br>Peak: 13 (2025-06-04)<br>Mean ADP: 2.1\",\"<b>MOUNT LAUREL HOLD ROOM<\\/b><br>NJ | Hold/Staging<br>Peak: 26 (2025-06-03)<br>Mean ADP: 5.5\",\"<b>MOBILE HOLDROOM<\\/b><br>AL | Hold/Staging<br>Peak: 35 (2025-06-24)<br>Mean ADP: 2.7\",\"<b>MONROE COUNTY JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 3 (2025-01-27)<br>Mean ADP: 0.2\",\"<b>MONTGOMERY CO MAC SIM BUTLER D.F.<\\/b><br>AL | Federal<br>Peak: 2 (2024-11-20)<br>Mean ADP: 0.3\",\"<b>MIAMI STAGING FACILITY<\\/b><br>FL | Hold/Staging<br>Peak: 176 (2025-01-31)<br>Mean ADP: 16.5\",\"<b>MONTGOMERY HOLD RM<\\/b><br>TX | Hold/Staging<br>Peak: 221 (2025-08-21)<br>Mean ADP: 50\",\"<b>NEWBURGH HOLDING<\\/b><br>NY | Hold/Staging<br>Peak: 10 (2025-07-29)<br>Mean ADP: 1.5\",\"<b>NEW/INS OS HOLD ROOM<\\/b><br>NJ | Hold/Staging<br>Peak: 12 (2024-11-21)<br>Mean ADP: 0.8\",\"<b>NEW ORLEANS HOLD ROOM<\\/b><br>LA | Hold/Staging<br>Peak: 5 (2025-06-11)<br>Mean ADP: 0.4\",\"<b>NORFOLK SUB-OFFICE HOLD<\\/b><br>VA | Hold/Staging<br>Peak: 16 (2025-08-21)<br>Mean ADP: 2\",\"<b>NORTH PLATTE HOLD ROOM<\\/b><br>NE | Hold/Staging<br>Peak: 13 (2025-03-08)<br>Mean ADP: 0.1\",\"<b>NASHVILLE HOLD ROOM<\\/b><br>TN | Hold/Staging<br>Peak: 75 (2025-05-04)<br>Mean ADP: 0.7\",\"<b>NYC HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 228 (2025-06-05)<br>Mean ADP: 40.9\",\"<b>NYE COUNTY SHERIFF-PAHRUMP<\\/b><br>NV | Non-Dedicated<br>Peak: 90 (2024-10-08)<br>Mean ADP: 7.1\",\"<b>OAKDALE HOLDING ROOM<\\/b><br>LA | Hold/Staging<br>Peak: 14 (2025-09-12)<br>Mean ADP: 0.1\",\"<b>OGDEN HOLD ROOM<\\/b><br>UT | Hold/Staging<br>Peak: 13 (2025-09-23)<br>Mean ADP: 1.3\",\"<b>OKLAHOMA CITY HOLD ROOM.<\\/b><br>OK | Hold/Staging<br>Peak: 79 (2025-09-24)<br>Mean ADP: 8.5\",\"<b>OMAHA FO HOLD<\\/b><br>NE | Hold/Staging<br>Peak: 73 (2025-06-11)<br>Mean ADP: 7.2\",\"<b>ORLANDO HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 126 (2025-06-04)<br>Mean ADP: 19.6\",\"<b>PECOS HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 28 (2025-08-01)<br>Mean ADP: 1.8\",\"<b>PDN HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 36 (2025-06-13)<br>Mean ADP: 0.1\",\"<b>PHI DISTRICT OFFICE<\\/b><br>PA | Hold/Staging<br>Peak: 33 (2025-06-05)<br>Mean ADP: 6.7\",\"<b>PHOENIX DIST OFFICE<\\/b><br>AZ | Hold/Staging<br>Peak: 90 (2025-05-21)<br>Mean ADP: 25.7\",\"<b>PITTSBURGH HOLDROOM<\\/b><br>PA | Hold/Staging<br>Peak: 19 (2025-06-03)<br>Mean ADP: 2.4\",\"<b>PIKE COUNTY ERO HOLD ROOM<\\/b><br>PA | Hold/Staging<br>Peak: 7 (2025-06-05)<br>Mean ADP: 1.4\",\"<b>PLATTE COUNTY JAIL<\\/b><br>WY | Federal<br>Peak: 11 (2025-07-11)<br>Mean ADP: 3\",\"<b>PORTLAND, ME HOLDROOM<\\/b><br>ME | Hold/Staging<br>Peak: 3 (2025-06-05)<br>Mean ADP: 0.1\",\"<b>PORTLAND DISTRICT OFFICE<\\/b><br>OR | Hold/Staging<br>Peak: 19 (2025-01-26)<br>Mean ADP: 2\",\"<b>PRAIRIELAND SUBOFFICE HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 81 (2025-09-20)<br>Mean ADP: 0.9\",\"<b>PROHOLD<\\/b><br>RI | Hold/Staging<br>Peak: 8 (2025-04-11)<br>Mean ADP: 1.3\",\"<b>PROVO HOLD ROOM<\\/b><br>UT | Hold/Staging<br>Peak: 10 (2025-08-22)<br>Mean ADP: 1.3\",\"<b>PUEBLO HOLDROOM<\\/b><br>CO | Hold/Staging<br>Peak: 15 (2025-04-27)<br>Mean ADP: 1.1\",\"<b>RICHMOND SUB-OFFICE HOLD<\\/b><br>VA | Hold/Staging<br>Peak: 277 (2025-09-07)<br>Mean ADP: 16.2\",\"<b>RALEIGH HOLD ROOM<\\/b><br>NC | Hold/Staging<br>Peak: 14 (2025-07-11)<br>Mean ADP: 3.7\",\"<b>REDDING HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 7 (2025-08-26)<br>Mean ADP: 0.6\",\"<b>RENO HOLD ROOM<\\/b><br>NV | Hold/Staging<br>Peak: 10 (2025-05-05)<br>Mean ADP: 0.2\",\"<b>RIO GRANDE VALLEY STAGING<\\/b><br>TX | Hold/Staging<br>Peak: 21 (2025-02-06)<br>Mean ADP: 0.6\",\"<b>RICHLAND HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 4 (2025-02-05)<br>Mean ADP: 0.3\",\"<b>ROCK ISLAND HOLD ROOM<\\/b><br>IL | Hold/Staging<br>Peak: 6 (2025-03-07)<br>Mean ADP: 0.8\",\"<b>ROANOKE SUB-OFFICE HOLD ROOM<\\/b><br>VA | Hold/Staging<br>Peak: 6 (2025-05-13)<br>Mean ADP: 0.7\",\"<b>ROANOKE CITY JAIL<\\/b><br>VA | Federal<br>Peak: 13 (2025-09-08)<br>Mean ADP: 1.4\",\"<b>RAPID CITY HOLD ROOM<\\/b><br>SD | Hold/Staging<br>Peak: 7 (2025-08-06)<br>Mean ADP: 0.3\",\"<b>ROSWELL HOLD ROOM<\\/b><br>NM | Hold/Staging<br>Peak: 16 (2025-09-17)<br>Mean ADP: 2.1\",\"<b>SANTA ANA DRO HOLDROOM<\\/b><br>CA | Hold/Staging<br>Peak: 150 (2025-06-11)<br>Mean ADP: 11.3\",\"<b>SACRAMENTO HOLD<\\/b><br>CA | Hold/Staging<br>Peak: 35 (2025-07-27)<br>Mean ADP: 3.3\",\"<b>SAN ANGELO HOLDROOM<\\/b><br>TX | Hold/Staging<br>Peak: 20 (2025-01-21)<br>Mean ADP: 3.3\",\"<b>SAN JUAN SUB-OFFICE HOLD ROOM<\\/b><br>PR | Hold/Staging<br>Peak: 50 (2025-06-04)<br>Mean ADP: 3.1\",\"<b>SALISBURY HOLD ROOM<\\/b><br>MD | Hold/Staging<br>Peak: 23 (2025-08-05)<br>Mean ADP: 2.1\",\"<b>SALINE COUNTY JAIL<\\/b><br>NE | Non-Dedicated<br>Peak: 7 (2025-09-09)<br>Mean ADP: 0\",\"<b>SAN BERNARDINO HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 38 (2025-06-20)<br>Mean ADP: 5.6\",\"<b>SEATTLE FIELD OFFICE HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 59 (2025-06-05)<br>Mean ADP: 4.7\",\"<b>SIOUX FALLS HOLD ROOM<\\/b><br>SD | Hold/Staging<br>Peak: 20 (2025-08-29)<br>Mean ADP: 0.5\",\"<b>SFR HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 44 (2025-06-04)<br>Mean ADP: 4.8\",\"<b>ST. GEORGE, UT HOLDROOM<\\/b><br>UT | Hold/Staging<br>Peak: 9 (2025-01-26)<br>Mean ADP: 0.7\",\"<b>SIOUX COUNTY JAIL<\\/b><br>IA | Federal<br>Peak: 10 (2025-09-08)<br>Mean ADP: 0.5\",\"<b>SAN JUAN AIRPORT HOLD ROOM<\\/b><br>PR | Hold/Staging<br>Peak: 24 (2024-12-22)<br>Mean ADP: 1.6\",\"<b>SALT LAKE CITY HOLD ROOM<\\/b><br>UT | Hold/Staging<br>Peak: 48 (2025-07-09)<br>Mean ADP: 10.8\",\"<b>SANTA MARIA SUB OFFICE ERO<\\/b><br>CA | Hold/Staging<br>Peak: 19 (2025-09-12)<br>Mean ADP: 3.4\",\"<b>SAN ANTONIO DRO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 145 (2025-06-04)<br>Mean ADP: 19.6\",\"<b>SND DISTRICT STAGING<\\/b><br>CA | Hold/Staging<br>Peak: 68 (2025-09-19)<br>Mean ADP: 15.7\",\"<b>SNJ HOLD ROOM<\\/b><br>CA | Hold/Staging<br>Peak: 2 (2024-12-03)<br>Mean ADP: 0\",\"<b>ERO HOLD ROOM (SPRINGFIELD MO)<\\/b><br>MO | Hold/Staging<br>Peak: 62 (2025-09-24)<br>Mean ADP: 1.2\",\"<b>BISHOP HENRY WHIPPLE FED BLDG<\\/b><br>MN | Hold/Staging<br>Peak: 87 (2025-02-12)<br>Mean ADP: 11.5\",\"<b>SPOKANE HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 17 (2025-04-28)<br>Mean ADP: 1.7\",\"<b>SAINT ALBANS HOLD ROOM<\\/b><br>VT | Hold/Staging<br>Peak: 7 (2024-11-12)<br>Mean ADP: 0.4\",\"<b>SOUTH TEXAS/PEARSALL HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 51 (2025-07-03)<br>Mean ADP: 4.8\",\"<b>STOCKTON STAGING FACILITY<\\/b><br>CA | Hold/Staging<br>Peak: 14 (2025-07-17)<br>Mean ADP: 2.1\",\"<b>ST. LOUIS HOLDROOM<\\/b><br>MO | Hold/Staging<br>Peak: 36 (2025-09-02)<br>Mean ADP: 3.8\",\"<b>STUART HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 53 (2025-09-18)<br>Mean ADP: 3\",\"<b>SIOUX CITY HOLD ROOM<\\/b><br>IA | Hold/Staging<br>Peak: 3 (2024-11-04)<br>Mean ADP: 0.1\",\"<b>SYRACUSE HOLD ROOM<\\/b><br>NY | Hold/Staging<br>Peak: 14 (2025-09-15)<br>Mean ADP: 0.6\",\"<b>TALLAHASSEE HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 45 (2025-08-20)<br>Mean ADP: 6.5\",\"<b>TAMPA HOLD ROOM<\\/b><br>FL | Hold/Staging<br>Peak: 84 (2025-08-08)<br>Mean ADP: 16.5\",\"<b>TELLER COUNTY JAIL<\\/b><br>CO | Non-Dedicated<br>Peak: 2 (2025-02-02)<br>Mean ADP: 0\",\"<b>TWIN FALLS HOLD ROOM<\\/b><br>ID | Hold/Staging<br>Peak: 6 (2025-01-15)<br>Mean ADP: 0.4\",\"<b>TURNER GUIFORD KNIGHT (TGK) JAIL<\\/b><br>FL | Non-Dedicated<br>Peak: 27 (2025-08-22)<br>Mean ADP: 3.8\",\"<b>TOM GREEN CTY JAIL<\\/b><br>TX | Federal<br>Peak: 15 (2025-03-21)<br>Mean ADP: 1.9\",\"<b>TEX HEALTH HUGULEY HOSP<\\/b><br>TX | Medical<br>Peak: 4 (2025-07-16)<br>Mean ADP: 0.5\",\"<b>TITUS COUNTY JAIL<\\/b><br>TX | Federal<br>Peak: 6 (2025-03-28)<br>Mean ADP: 0.9\",\"<b>WESTERN TENNESSEE DET. FAC.<\\/b><br>TN | Federal<br>Peak: 39 (2025-09-12)<br>Mean ADP: 1.6\",\"<b>TUCSON INS HOLD ROOM<\\/b><br>AZ | Hold/Staging<br>Peak: 15 (2025-06-06)<br>Mean ADP: 3.2\",\"<b>TULSA HOLD ROOM<\\/b><br>OK | Hold/Staging<br>Peak: 16 (2025-09-17)<br>Mean ADP: 1.7\",\"<b>TEXARKANA HOLDROOM<\\/b><br>AR | Hold/Staging<br>Peak: 6 (2025-05-21)<br>Mean ADP: 0.6\",\"<b>VAL VERDE DETENTION CENTER<\\/b><br>TX | Federal<br>Peak: 35 (2025-06-17)<br>Mean ADP: 3.6\",\"<b>VENTURA CUSTODY CASE<\\/b><br>CA | Hold/Staging<br>Peak: 80 (2025-07-11)<br>Mean ADP: 5.9\",\"<b>VRK PRCS<\\/b><br>NY | Hold/Staging<br>Peak: 12 (2025-09-23)<br>Mean ADP: 0.2\",\"<b>SHREVEPORT HOLD ROOM<\\/b><br>LA | Hold/Staging<br>Peak: 8 (2025-08-28)<br>Mean ADP: 1.1\",\"<b>WASHINGTON FIELD OFFICE<\\/b><br>VA | Hold/Staging<br>Peak: 127 (2025-08-23)<br>Mean ADP: 17.3\",\"<b>WACO DRO HOLD ROOM<\\/b><br>TX | Hold/Staging<br>Peak: 24 (2025-06-30)<br>Mean ADP: 4.9\",\"<b>WESTMINSTER CUSTODY<\\/b><br>CA | Hold/Staging<br>Peak: 8 (2025-07-04)<br>Mean ADP: 1.6\",\"<b>WICHITA HOLDROOM<\\/b><br>KS | Hold/Staging<br>Peak: 2 (2025-05-31)<br>Mean ADP: 0\",\"<b>WENATCHEE HOLD ROOM<\\/b><br>WA | Hold/Staging<br>Peak: 4 (2024-11-04)<br>Mean ADP: 0.2\",\"<b>WILLIAMSPORT HOLD ROOM<\\/b><br>PA | Hold/Staging<br>Peak: 21 (2025-08-19)<br>Mean ADP: 0.5\",\"<b>EASTERN REGIONAL JAIL<\\/b><br>WV | Federal<br>Peak: 16 (2025-03-11)<br>Mean ADP: 1.1\",\"<b>YAKIMA SUB-OFFICE<\\/b><br>WA | Hold/Staging<br>Peak: 12 (2025-06-04)<br>Mean ADP: 1.2\",\"<b>YORK HOLD ROOM<\\/b><br>PA | Hold/Staging<br>Peak: 16 (2025-04-23)<br>Mean ADP: 3\",\"<b>YUMA HOLDROOM<\\/b><br>AZ | Hold/Staging<br>Peak: 8 (2025-07-31)<br>Mean ADP: 1\"],null,[\"ALBUQUERQUE HOLD ROOM (NM: peak 45)\",\"GUAM ERO HOLD ROOM (GU: peak 4)\",\"AGUADILLA SPC (PR: peak 60)\",\"ALBANY HOLDROOM (NY: peak 16)\",\"ALAMOSA HOLDROOM (CO: peak 7)\",\"AMARILLO HOLD ROOM (TX: peak 17)\",\"ANCHORAGE JAIL (AK: peak 43)\",\"ANCHORAGE SUB-OFFICE HOLD ROOM (AK: peak 5)\",\"ATLANTA PRETRIAL DETN CTR (GA: peak 3)\",\"ATLANTA DIST. HOLD RM (GA: peak 168)\",\"ATHENS, TX HOLD ROOM (TX: peak 14)\",\"AUSTIN DRO HOLD ROOM (TX: peak 48)\",\"ARIZONA STATE PRISON - YUMA (AZ: peak 3)\",\"BALDWIN COUNTY COR. CENTER (AL: peak 28)\",\"BALTIMORE HOLD ROOM (MD: peak 120)\",\"BIRMINGHAM HOLD ROOM (AL: peak 18)\",\"BAKERFIELD HOLD (CA: peak 49)\",\"BOISE HOLD ROOM (ID: peak 8)\",\"GUAYNABO MDC (SAN JUAN) (PR: peak 16)\",\"BOSTON HOLDROOM (MA: peak 206)\",\"BROWARD COUNTY JAIL (FL: peak 14)\",\"BROOKS COUNTY JAIL (CONTRACT) (TX: peak 90)\",\"BROADVIEW SERVICE STAGING (IL: peak 245)\",\"BIG SPRING HOLD ROOM (TX: peak 10)\",\"BUFFALO HOLD ROOM (NY: peak 45)\",\"CACHE CO. JAIL (UT: peak 13)\",\"CASCADE COUNTY JAIL, MT (MT: peak 5)\",\"BUFFALO USBP HOLD ROOM (NY: peak 20)\",\"Cabarrus County Jail (NC: peak 6)\",\"CHARLOTTE AMALIE HOLDROOM (VI: peak 4)\",\"CHAVEZ DET CRT (NM: peak 16)\",\"CHICAGO HOLD ROOM (IL: peak 7)\",\"CHARLESTON, SC HOLD ROOM (SC: peak 69)\",\"CHAMPLAIN HOLD ROOM (NY: peak 8)\",\"CHEYENNE HOLDROOM (WY: peak 3)\",\"CINCINNATI HOLDROOM (OH: peak 4)\",\"CENTRAL ISLIP HOLD ROOM (NY: peak 45)\",\"CLEVELAND HOLD ROOM (OH: peak 14)\",\"COLUMBUS HOLDROOM (OH: peak 10)\",\"CHARLOTTE HOLD ROOM (NC: peak 48)\",\"CHATTANOOGA HOLD ROOM (TN: peak 12)\",\"COLUMBIA, SC HOLDROOM (SC: peak 31)\",\"COBB CO SHERIFFS OFC ADULT DET CTR (GA: peak 4)\",\"CRAIG HOLDROOM (CO: peak 4)\",\"CEDAR RAPIDS HOLD ROOM (IA: peak 17)\",\"CORPUS CHRISTI EOR HOLD ROOM (TX: peak 8)\",\"COLO SPRINGS DEN HSI HOLD (CO: peak 7)\",\"CASPER HOLDROOM (WY: peak 6)\",\"DALLAS F.O. HOLD (TX: peak 225)\",\"DENVER HOLD ROOM (CO: peak 35)\",\"DETROIT HOLDROOM (MI: peak 47)\",\"DEL RIO DRO HOLD ROOM (TX: peak 12)\",\"DORCHESTER CO DET CTR (SC: peak 10)\",\"DES MOINES HOLD ROOM (IA: peak 3)\",\"DURANGO HOLDROOM (CO: peak 6)\",\"DOVER HOLDROOM (DE: peak 10)\",\"EL PASO COUNTY DETENTION FACILITY (TX: peak 95)\",\"EGP CPC HOLDING (TX: peak 2)\",\"EL PASO SOFT SIDED FACILITY (TX: peak 1606)\",\"ETOWAH ERO HOLD ROOM (AL: peak 2)\",\"EUGENE HOLDROOM (OR: peak 9)\",\"FAYETTEVILLE HOLD ROOM (AR: peak 9)\",\"FERNDALE HOLD ROOM (WA: peak 6)\",\"FINNEY COUNTY JAIL (KS: peak 11)\",\"DADE CORRECTIONAL INST (FL: peak 7)\",\"FLORIDA SOFT-SIDED FACILITY-SOUTH (FL: peak 1482)\",\"FORT MYERS ERO HOLDROOM (FL: peak 29)\",\"FRANKLIN COUNTY JAIL (PA: peak 2)\",\"FREDERICK HOLDROOM (CO: peak 7)\",\"FRESNO HOLDROOM (CA: peak 22)\",\"FORT SMITH HOLDROOM (AR: peak 4)\",\"GARVIN COUNTY JAIL (OK: peak 15)\",\"GASTON COUNTY JAIL (NC: peak 6)\",\"GRAND JUNCTION HOLDROOM (CO: peak 7)\",\"GLENDALE POLICE DEPT (CA: peak 22)\",\"GRAND FORKS HOLD ROOM (ND: peak 13)\",\"GRAND RAPIDS HOLDROOM (MI: peak 9)\",\"GREER HOLD ROOM (SC: peak 7)\",\"GLENWOOD SPRINGS HOLDROOM (CO: peak 10)\",\"HAILE DET. CENTER (ID: peak 2)\",\"HARTFORD OFFICE (CT: peak 37)\",\"HARRISONBURG HOLD ROOM (VA: peak 11)\",\"HEL DISTRICT CUSTODY (MT: peak 2)\",\"HENDERSONVILLE HOLD ROOM (NC: peak 5)\",\"ERO HONOLULU SUB-OFFICE HOLD ROOM (HI: peak 4)\",\"HILLSBOROUGH COUNTY JAIL (FL: peak 40)\",\"HARLINGEN HOLD ROOM (TX: peak 118)\",\"HOUSTON FO HOLDROOM (TX: peak 18)\",\"IDAHO FALLS HOLD ROOM (ID: peak 5)\",\"IMPERIAL SUB OFFICE HOLD ROOM (CA: peak 12)\",\"INDIANAPOLIS HOLD ROOM (IN: peak 130)\",\"AZ REM OP COORD CENTER (AROCC) (AZ: peak 195)\",\"JACKSON MS HOLD ROOM (MS: peak 23)\",\"JACKSONVILLE SUB-OFFICE (FL: peak 35)\",\"JACK HARWELL DETENTION CENTER (TX: peak 6)\",\"KANSAS CITY HOLDROOM (MO: peak 64)\",\"KARNES CTY CORR CTR (TX: peak 10)\",\"KARNES COUNTY CIVIL DET. FACILITY (TX: peak 9)\",\"KNOXVILLE HOLD ROOM (TN: peak 20)\",\"KROME/MIAMI HUB (FL: peak 54)\",\"KROME HOLD ROOM (FL: peak 600)\",\"LARAMIE COUNTY JAIL (WY: peak 8)\",\"LAS CRUCES HOLD ROOM (NM: peak 7)\",\"LAWRENCE CO. JAIL, SD (SD: peak 5)\",\"LUBBOCK HOLD ROOM (TX: peak 17)\",\"LINCOLN COUNTY SHERIFF'S (MO: peak 4)\",\"LOS CUST CASE (CA: peak 455)\",\"LOUISVILLE HOLD ROOM (KY: peak 23)\",\"LITTLE ROCK HOLD ROOM (AR: peak 27)\",\"LAREDO DETENTION CENTER HOLD ROOM (TX: peak 115)\",\"LAS VEGAS HOLD ROOM (NV: peak 68)\",\"MANCHESTER HOLDROOM (NH: peak 9)\",\"MARTIN COUNTY JAIL (FL: peak 24)\",\"MCALLEN HOLD ROOM (TX: peak 59)\",\"MEDFORD SUB-OFFICE (OR: peak 14)\",\"MEMPHIS HOLD ROOM (TN: peak 25)\",\"MIAMI (MIRAMAR) HOLD ROOM (FL: peak 94)\",\"MIDLAND DETENTION CENTER (TX: peak 13)\",\"MILWAUKEE HOLDROOM (WI: peak 22)\",\"MINICASSIA DET. CENTER (ID: peak 8)\",\"MIDLAND, TX ERO HOLDROOM (TX: peak 13)\",\"MOUNT LAUREL HOLD ROOM (NJ: peak 26)\",\"MOBILE HOLDROOM (AL: peak 35)\",\"MONROE COUNTY JAIL (FL: peak 3)\",\"MONTGOMERY CO MAC SIM BUTLER D.F. (AL: peak 2)\",\"MIAMI STAGING FACILITY (FL: peak 176)\",\"MONTGOMERY HOLD RM (TX: peak 221)\",\"NEWBURGH HOLDING (NY: peak 10)\",\"NEW/INS OS HOLD ROOM (NJ: peak 12)\",\"NEW ORLEANS HOLD ROOM (LA: peak 5)\",\"NORFOLK SUB-OFFICE HOLD (VA: peak 16)\",\"NORTH PLATTE HOLD ROOM (NE: peak 13)\",\"NASHVILLE HOLD ROOM (TN: peak 75)\",\"NYC HOLD ROOM (NY: peak 228)\",\"NYE COUNTY SHERIFF-PAHRUMP (NV: peak 90)\",\"OAKDALE HOLDING ROOM (LA: peak 14)\",\"OGDEN HOLD ROOM (UT: peak 13)\",\"OKLAHOMA CITY HOLD ROOM. (OK: peak 79)\",\"OMAHA FO HOLD (NE: peak 73)\",\"ORLANDO HOLD ROOM (FL: peak 126)\",\"PECOS HOLD ROOM (TX: peak 28)\",\"PDN HOLD ROOM (TX: peak 36)\",\"PHI DISTRICT OFFICE (PA: peak 33)\",\"PHOENIX DIST OFFICE (AZ: peak 90)\",\"PITTSBURGH HOLDROOM (PA: peak 19)\",\"PIKE COUNTY ERO HOLD ROOM (PA: peak 7)\",\"PLATTE COUNTY JAIL (WY: peak 11)\",\"PORTLAND, ME HOLDROOM (ME: peak 3)\",\"PORTLAND DISTRICT OFFICE (OR: peak 19)\",\"PRAIRIELAND SUBOFFICE HOLD ROOM (TX: peak 81)\",\"PROHOLD (RI: peak 8)\",\"PROVO HOLD ROOM (UT: peak 10)\",\"PUEBLO HOLDROOM (CO: peak 15)\",\"RICHMOND SUB-OFFICE HOLD (VA: peak 277)\",\"RALEIGH HOLD ROOM (NC: peak 14)\",\"REDDING HOLD ROOM (CA: peak 7)\",\"RENO HOLD ROOM (NV: peak 10)\",\"RIO GRANDE VALLEY STAGING (TX: peak 21)\",\"RICHLAND HOLD ROOM (WA: peak 4)\",\"ROCK ISLAND HOLD ROOM (IL: peak 6)\",\"ROANOKE SUB-OFFICE HOLD ROOM (VA: peak 6)\",\"ROANOKE CITY JAIL (VA: peak 13)\",\"RAPID CITY HOLD ROOM (SD: peak 7)\",\"ROSWELL HOLD ROOM (NM: peak 16)\",\"SANTA ANA DRO HOLDROOM (CA: peak 150)\",\"SACRAMENTO HOLD (CA: peak 35)\",\"SAN ANGELO HOLDROOM (TX: peak 20)\",\"SAN JUAN SUB-OFFICE HOLD ROOM (PR: peak 50)\",\"SALISBURY HOLD ROOM (MD: peak 23)\",\"SALINE COUNTY JAIL (NE: peak 7)\",\"SAN BERNARDINO HOLD ROOM (CA: peak 38)\",\"SEATTLE FIELD OFFICE HOLD ROOM (WA: peak 59)\",\"SIOUX FALLS HOLD ROOM (SD: peak 20)\",\"SFR HOLD ROOM (CA: peak 44)\",\"ST. GEORGE, UT HOLDROOM (UT: peak 9)\",\"SIOUX COUNTY JAIL (IA: peak 10)\",\"SAN JUAN AIRPORT HOLD ROOM (PR: peak 24)\",\"SALT LAKE CITY HOLD ROOM (UT: peak 48)\",\"SANTA MARIA SUB OFFICE ERO (CA: peak 19)\",\"SAN ANTONIO DRO HOLD ROOM (TX: peak 145)\",\"SND DISTRICT STAGING (CA: peak 68)\",\"SNJ HOLD ROOM (CA: peak 2)\",\"ERO HOLD ROOM (SPRINGFIELD MO) (MO: peak 62)\",\"BISHOP HENRY WHIPPLE FED BLDG (MN: peak 87)\",\"SPOKANE HOLD ROOM (WA: peak 17)\",\"SAINT ALBANS HOLD ROOM (VT: peak 7)\",\"SOUTH TEXAS/PEARSALL HOLD ROOM (TX: peak 51)\",\"STOCKTON STAGING FACILITY (CA: peak 14)\",\"ST. LOUIS HOLDROOM (MO: peak 36)\",\"STUART HOLD ROOM (FL: peak 53)\",\"SIOUX CITY HOLD ROOM (IA: peak 3)\",\"SYRACUSE HOLD ROOM (NY: peak 14)\",\"TALLAHASSEE HOLD ROOM (FL: peak 45)\",\"TAMPA HOLD ROOM (FL: peak 84)\",\"TELLER COUNTY JAIL (CO: peak 2)\",\"TWIN FALLS HOLD ROOM (ID: peak 6)\",\"TURNER GUIFORD KNIGHT (TGK) JAIL (FL: peak 27)\",\"TOM GREEN CTY JAIL (TX: peak 15)\",\"TEX HEALTH HUGULEY HOSP (TX: peak 4)\",\"TITUS COUNTY JAIL (TX: peak 6)\",\"WESTERN TENNESSEE DET. FAC. (TN: peak 39)\",\"TUCSON INS HOLD ROOM (AZ: peak 15)\",\"TULSA HOLD ROOM (OK: peak 16)\",\"TEXARKANA HOLDROOM (AR: peak 6)\",\"VAL VERDE DETENTION CENTER (TX: peak 35)\",\"VENTURA CUSTODY CASE (CA: peak 80)\",\"VRK PRCS (NY: peak 12)\",\"SHREVEPORT HOLD ROOM (LA: peak 8)\",\"WASHINGTON FIELD OFFICE (VA: peak 127)\",\"WACO DRO HOLD ROOM (TX: peak 24)\",\"WESTMINSTER CUSTODY (CA: peak 8)\",\"WICHITA HOLDROOM (KS: peak 2)\",\"WENATCHEE HOLD ROOM (WA: peak 4)\",\"WILLIAMSPORT HOLD ROOM (PA: peak 21)\",\"EASTERN REGIONAL JAIL (WV: peak 16)\",\"YAKIMA SUB-OFFICE (WA: peak 12)\",\"YORK HOLD ROOM (PA: peak 16)\",\"YUMA HOLDROOM (AZ: peak 8)\"],{\"interactive\":false,\"permanent\":false,\"direction\":\"auto\",\"opacity\":1,\"offset\":[0,0],\"textsize\":\"10px\",\"textOnly\":false,\"className\":\"\",\"sticky\":true},null]},{\"method\":\"addLegend\",\"args\":[{\"colors\":[\"#E41A1C\",\"#A65628\",\"#4DAF4A\",\"#FF7F00\",\"#377EB8\",\"#984EA3\",\"#333333\"],\"labels\":[\"Dedicated\",\"Non-Dedicated\",\"Federal\",\"Hold/Staging\",\"Family/Youth\",\"Medical\",\"Unclassified\"],\"na_color\":null,\"na_label\":\"NA\",\"opacity\":0.5,\"position\":\"bottomright\",\"type\":\"factor\",\"title\":\"Facility type\",\"extra\":null,\"layerId\":null,\"className\":\"info legend\",\"group\":null}]},{\"method\":\"addLayersControl\",\"args\":[[],[\"Peak < 2\",\"Peak ≥ 2\"],{\"collapsed\":false,\"autoZIndex\":true,\"position\":\"topright\"}]},{\"method\":\"addSearchFeatures\",\"args\":[[\"Peak < 2\",\"Peak ≥ 2\"],{\"openPopup\":true,\"propertyName\":\"label\",\"moveToLocation\":true,\"zoom\":9,\"container\":\"\",\"minLength\":1,\"initial\":false,\"casesensitive\":false,\"autoType\":true,\"delayType\":400,\"tooltipLimit\":-1,\"tipAutoSubmit\":true,\"firstTipSubmit\":false,\"autoResize\":true,\"collapsed\":true,\"autoCollapse\":false,\"autoCollapseTime\":1200,\"textErr\":\"Location Not Found\",\"textCancel\":\"Cancel\",\"textPlaceholder\":\"Search...\",\"position\":\"topleft\",\"hideMarkerOnCollapse\":true,\"marker\":{\"animate\":true,\"circle\":{\"radius\":10,\"weight\":3,\"color\":\"#e03\",\"stroke\":true,\"fill\":false}}}]},{\"method\":\"addControl\",\"args\":[\"<style>\\n      /* Force legend text left in Quarto/Bootstrap contexts */\\n      .leaflet-container .leaflet-control {\\n        text-align: left !important;\\n      }\\n      .leaflet-container .leaflet-control .legend {\\n        text-align: left !important;\\n      }\\n\\n      /* Make the color swatch and label behave like a left-aligned row */\\n      .leaflet-container .leaflet-control .legend i {\\n        display: inline-block !important;\\n        width: 14px !important;\\n        height: 14px !important;\\n        margin: 0 8px 0 0 !important;\\n        vertical-align: middle !important;\\n      }\\n      .leaflet-container .leaflet-control .legend span {\\n        display: inline !important;\\n        vertical-align: middle !important;\\n      }\\n    <\\/style>\",\"bottomright\",null,\"info legend\"]}],\"limits\":{\"lat\":[13.4760946,61.2185041],\"lng\":[-157.8638944,145.7028775]}},\"evals\":[],\"jsHooks\":[]}</script>\n```\n\n\nDDP facilities not in ICE FY25 annual statistics, sized by FY25 peak population\n:::\n:::\n\n:::\n\n## Unreported detention: Final Biden quarter vs recent Trump quarter {#sec-period-comparison}\n\nThe preceding sections establish which DDP facilities are absent from the ICE FY25 annual statistics. Here we compare the **unreported population**---detainees held at those unmatched facilities---during the final three months of the Biden administration versus a comparable window under the Trump administration.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiden_from <- as.Date(\"2024-10-20\")\nbiden_to   <- as.Date(\"2025-01-19\")\ntrump_from <- as.Date(\"2025-07-01\")\ntrump_to   <- as.Date(\"2025-09-30\")\n```\n:::\n\n\n-   **Biden final quarter**: 2024-10-20 to 2025-01-19 (92 days)\n-   **Trump recent quarter**: 2025-07-01 to 2025-09-30 (92 days)\n\n### Aggregate unreported population\n\n\n::: {#tbl-period-totals .cell tbl-cap='Unreported DDP population by period (facilities not in ICE FY25)'}\n\n```{.r .cell-code}\nbind_rows(biden_unmatched, trump_unmatched) |>\n  filter(peak_pop > 0) |>\n  group_by(period, peak_class) |>\n  summarise(\n    Facilities = n(),\n    `Total ADP` = round(sum(mean_pop)),\n    .groups = \"drop\"\n  ) |>\n  arrange(peak_class, period) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|period |peak_class | Facilities| Total ADP|\n|:------|:----------|----------:|---------:|\n|Biden  |Peak < 2   |        109|         8|\n|Trump  |Peak < 2   |        129|        14|\n|Biden  |Peak ≥ 2   |        206|       396|\n|Trump  |Peak ≥ 2   |        292|      3233|\n\n\n:::\n:::\n\n\n\n::: {#tbl-period-headline .cell tbl-cap='Unreported population totals (Peak ≥ 2 facilities only)'}\n\n```{.r .cell-code}\nbind_rows(biden_unmatched, trump_unmatched) |>\n  filter(peak_pop > 0, peak_class == \"Peak \\u2265 2\") |>\n  group_by(period) |>\n  summarise(\n    Facilities = n(),\n    `Total ADP` = round(sum(mean_pop)),\n    `Mean ADP per facility` = round(sum(mean_pop) / n(), 1),\n    .groups = \"drop\"\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|period | Facilities| Total ADP| Mean ADP per facility|\n|:------|----------:|---------:|---------------------:|\n|Biden  |        206|       396|                   1.9|\n|Trump  |        292|      3233|                  11.1|\n\n\n:::\n:::\n\n\nThis graph shows the distribution of population totals among the unmatched facilities in each period, with a horizontal line marking the average for each period. The six largest facilities are named. As you can see, the largest unreported opulation in the Biden period would not even be an outlier in the Trump period. Conversely, the three largest unreported facilities in the Trump period each held more people in this period that all the Biden facilities combined.\n\n:::{column-screen-inset-right}\n\n::: {.cell tbl-cap='Distribution plots for FY25 peak population compared between Biden and Trump'}\n\n```{.r .cell-code}\nsource(\"violin-plot.R\")\nviolin_plot\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/violin-plot-1.png){width=960}\n:::\n:::\n\n:::\n\n### By facility type\n\n\n::: {#tbl-period-type-composition .cell tbl-cap='Unreported facilities by type and period (ADP ≥ 2 only)'}\n\n```{.r .cell-code}\ntype_comp <- bind_rows(biden_unmatched, trump_unmatched) |>\n  filter(peak_pop > 0, adp_class == \"ADP \\u2265 2\") |>\n  group_by(period, type_grouped) |>\n  summarise(\n    Facilities = n(),\n    ADP = round(sum(mean_pop)),\n    .groups = \"drop\"\n  )\n\ntype_comp |>\n  pivot_wider(names_from = period,\n              values_from = c(Facilities, ADP),\n              values_fill = 0,\n              names_glue = \"{period} {.value}\") |>\n  mutate(\n    `ADP change` = `Trump ADP` - `Biden ADP`,\n    `% change` = if_else(\n      `Biden ADP` == 0, NA_real_,\n      round((`Trump ADP` / `Biden ADP` - 1) * 100, 1)\n    )\n  ) |>\n  arrange(desc(`Trump ADP`)) |>\n  kable(col.names = c(\"Facility type\",\n                       \"Biden fac.\", \"Trump fac.\",\n                       \"Biden ADP\", \"Trump ADP\",\n                       \"ADP change\", \"% change\"))\n```\n\n::: {.cell-output-display}\n\n\n|Facility type | Biden fac.| Trump fac.| Biden ADP| Trump ADP| ADP change| % change|\n|:-------------|----------:|----------:|---------:|---------:|----------:|--------:|\n|Hold/Staging  |         37|         91|       258|      1848|       1590|    616.3|\n|Dedicated     |          0|          1|         0|       808|        808|       NA|\n|Unclassified  |          8|         20|        32|       348|        316|    987.5|\n|Federal       |          1|         11|         7|        71|         64|    914.3|\n|Non-Dedicated |          2|         10|        14|        48|         34|    242.9|\n\n\n:::\n:::\n\n\n\n::: {#tbl-period-type-transient .cell tbl-cap='Transient facilities (Peak < 2) by type and period'}\n\n```{.r .cell-code}\nbind_rows(biden_unmatched, trump_unmatched) |>\n  filter(peak_pop > 0, peak_class == \"Peak < 2\") |>\n  group_by(period, type_grouped) |>\n  summarise(\n    Facilities = n(),\n    ADP = round(sum(mean_pop), 1),\n    .groups = \"drop\"\n  ) |>\n  pivot_wider(names_from = period,\n              values_from = c(Facilities, ADP),\n              values_fill = 0,\n              names_glue = \"{period} {.value}\") |>\n  arrange(desc(`Trump Facilities`)) |>\n  kable(col.names = c(\"Facility type\",\n                       \"Biden fac.\", \"Trump fac.\",\n                       \"Biden ADP\", \"Trump ADP\"))\n```\n\n::: {.cell-output-display}\n\n\n|Facility type | Biden fac.| Trump fac.| Biden ADP| Trump ADP|\n|:-------------|----------:|----------:|---------:|---------:|\n|Unclassified  |         77|        105|       5.4|      11.6|\n|Federal       |          4|          9|       0.2|       0.3|\n|Non-Dedicated |          9|          8|       1.3|       2.1|\n|Hold/Staging  |         17|          5|       0.5|       0.2|\n|Medical       |          2|          1|       0.1|       0.1|\n|Family/Youth  |          0|          1|       0.0|       0.0|\n\n\n:::\n:::\n\n\n### Facilities active in only one period\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiden_active <- biden_unmatched |> filter(peak_pop > 0, peak_class == \"Peak \\u2265 2\")\ntrump_active <- trump_unmatched |> filter(peak_pop > 0, peak_class == \"Peak \\u2265 2\")\n\nbiden_only_codes <- setdiff(biden_active$detention_facility_code,\n                             trump_active$detention_facility_code)\ntrump_only_codes <- setdiff(trump_active$detention_facility_code,\n                             biden_active$detention_facility_code)\n```\n:::\n\n\n\n::: {#tbl-biden-only .cell tbl-cap='Unreported facilities with Peak ≥ 2 active under Biden but not Trump'}\n\n```{.r .cell-code}\nif (length(biden_only_codes) > 0) {\n  biden_unmatched |>\n    filter(detention_facility_code %in% biden_only_codes) |>\n    arrange(desc(mean_pop)) |>\n    select(detention_facility, state, type_grouped, mean_pop, peak_pop) |>\n    mutate(mean_pop = round(mean_pop, 1)) |>\n    kable(col.names = c(\"Facility\", \"State\", \"Type\", \"Biden ADP\", \"Biden peak\")) \n}\n```\n\n::: {.cell-output-display}\n\n\n|Facility                           |State |Type          | Biden ADP| Biden peak|\n|:----------------------------------|:-----|:-------------|---------:|----------:|\n|NYE COUNTY SHERIFF-PAHRUMP         |NV    |Non-Dedicated |      12.0|         69|\n|GUAYNABO MDC (SAN JUAN)            |PR    |Federal       |       6.6|         12|\n|MONTGOMERY CO MAC SIM BUTLER D.F.  |AL    |Federal       |       0.9|          2|\n|BRONSON METHODIST HOSPITAL         |MI    |Unclassified  |       0.8|          2|\n|COBB CO SHERIFFS OFC ADULT DET CTR |GA    |Non-Dedicated |       0.6|          4|\n|SAINT ALBANS HOLD ROOM             |VT    |Hold/Staging  |       0.5|          7|\n|LINCOLN COUNTY SHERIFF'S           |MO    |Non-Dedicated |       0.4|          3|\n|ST. JOHN'S COUNTY JAIL             |FL    |Unclassified  |       0.4|          2|\n|METHODIST HOSPITAL TEXSAN          |TX    |Unclassified  |       0.4|          2|\n|WASHINGTON COUNTY JAIL             |MN    |Unclassified  |       0.4|          3|\n|ORANGE REGIONAL MED CTR            |NY    |Unclassified  |       0.2|          2|\n|LOMPOC FCI                         |CA    |Unclassified  |       0.2|          6|\n|COLUMBUS HOLDROOM                  |OH    |Hold/Staging  |       0.2|          9|\n|KARNES COUNTY CIVIL DET. FACILITY  |TX    |Family/Youth  |       0.1|          2|\n|KINNEY COUNTY JAIL                 |TX    |Unclassified  |       0.1|          4|\n|SIOUX CITY HOLD ROOM               |IA    |Hold/Staging  |       0.1|          3|\n|EL CENTRO REGIONAL MED CTR         |CA    |Unclassified  |       0.1|          2|\n|METHODIST HOSPITAL                 |TX    |Unclassified  |       0.1|          2|\n|SPRINGFIELD FED.MED.CNTR           |MO    |Unclassified  |       0.1|          2|\n|FCI VICTORVILLE                    |CA    |Unclassified  |       0.1|          7|\n|ST FRANCIS HOSPITAL                |GA    |Unclassified  |       0.1|          2|\n|CHANDLER REG MED CTR               |AZ    |Unclassified  |       0.1|          2|\n|CINCINNATI HOLDROOM                |OH    |Hold/Staging  |       0.0|          2|\n|SNJ HOLD ROOM                      |CA    |Hold/Staging  |       0.0|          2|\n\n\n:::\n:::\n\n\n24 unreported facilities (Peak ≥ 2) were active in the Biden period but fell below the threshold or had zero population in the Trump period. Of these, 2 had ADP ≥ 2 under Biden, contributing 19 ADP in total.\n\n\n::: {#tbl-trump-only .cell tbl-cap='Unreported facilities with Peak ≥ 2 active under Trump but not Biden (scroll for full list)'}\n\n```{.r .cell-code}\nif (length(trump_only_codes) > 0) {\n  trump_unmatched |>\n    filter(detention_facility_code %in% trump_only_codes) |>\n    arrange(desc(mean_pop)) |>\n    select(detention_facility, state, type_grouped, mean_pop, peak_pop) |>\n    mutate(mean_pop = round(mean_pop, 1)) |>\n    kable(col.names = c(\"Facility\", \"State\", \"Type\", \"Trump ADP\", \"Trump peak\")) |> \n    scroll_box(height = \"630px\")\n}\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div style=\"border: 1px solid #ddd; padding: 0px; overflow-y: scroll; height:630px; \"><table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> Facility </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> State </th>\n   <th style=\"text-align:left;position: sticky; top:0; background-color: #FFFFFF;\"> Type </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> Trump ADP </th>\n   <th style=\"text-align:right;position: sticky; top:0; background-color: #FFFFFF;\"> Trump peak </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> FLORIDA SOFT-SIDED FACILITY-SOUTH </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Dedicated </td>\n   <td style=\"text-align:right;\"> 808.4 </td>\n   <td style=\"text-align:right;\"> 1482 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EL PASO SOFT SIDED FACILITY </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 326.1 </td>\n   <td style=\"text-align:right;\"> 1606 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BAKER C. I. </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 176.1 </td>\n   <td style=\"text-align:right;\"> 667 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> URSULA CENTRALIZED PROCESSING CNTR </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 84.6 </td>\n   <td style=\"text-align:right;\"> 365 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BROOKS COUNTY JAIL (CONTRACT) </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 21.1 </td>\n   <td style=\"text-align:right;\"> 90 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TURNER GUIFORD KNIGHT (TGK) JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 14.9 </td>\n   <td style=\"text-align:right;\"> 27 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WESTERN TENNESSEE DET. FAC. </td>\n   <td style=\"text-align:left;\"> TN </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 12.6 </td>\n   <td style=\"text-align:right;\"> 74 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MARTIN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 7.4 </td>\n   <td style=\"text-align:right;\"> 24 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHRISTIAN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> KY </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 6.4 </td>\n   <td style=\"text-align:right;\"> 51 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WESTMINSTER CUSTODY </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 6.0 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> RIO VISTA BEHV HLTH HSP </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 5.2 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ERO HOLD ROOM (SPRINGFIELD MO) </td>\n   <td style=\"text-align:left;\"> MO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 5.0 </td>\n   <td style=\"text-align:right;\"> 62 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> OSCEOLA COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 4.5 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EASTERN REGIONAL JAIL </td>\n   <td style=\"text-align:left;\"> WV </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 4.5 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SW VIRGINIA REG JAIL AUTH-ABG FAC </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 4.0 </td>\n   <td style=\"text-align:right;\"> 47 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SIOUX COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> IA </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 4.0 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHAVEZ DET CRT </td>\n   <td style=\"text-align:left;\"> NM </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 3.5 </td>\n   <td style=\"text-align:right;\"> 16 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TOM GREEN CTY JAIL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 3.2 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LAWRENCE CO. JAIL, SD </td>\n   <td style=\"text-align:left;\"> SD </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 2.7 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GRAND RAPIDS HOLDROOM </td>\n   <td style=\"text-align:left;\"> MI </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 2.7 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NEW YORK PRESBYTERIAN HOSPITAL </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 2.4 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHESAPEAKE CITY JAIL </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 2.3 </td>\n   <td style=\"text-align:right;\"> 25 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CEDAR RAPIDS HOLD ROOM </td>\n   <td style=\"text-align:left;\"> IA </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 2.2 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CASCADE COUNTY JAIL, MT </td>\n   <td style=\"text-align:left;\"> MT </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 2.1 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HILLSBOROUGH COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 2.0 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WHITE MEMORIAL HOSPITAL </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.8 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SCOTT COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> IA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.8 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SYRACUSE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.8 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SEMINOLE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.7 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CACHE CO. JAIL </td>\n   <td style=\"text-align:left;\"> UT </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 1.7 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BUFFALO HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.7 </td>\n   <td style=\"text-align:right;\"> 17 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ST JOSEPH MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> WA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.7 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MINICASSIA DET. CENTER </td>\n   <td style=\"text-align:left;\"> ID </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 1.6 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LARAMIE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> WY </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 1.6 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> RIO GRANDE VALLEY STAGING </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.5 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MARION COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.5 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> COLO SPRINGS DEN HSI HOLD </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.5 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LIRS - LFSRM FORT COLLINS LTFC CO </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.5 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TEX HEALTH HUGULEY HOSP </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Medical </td>\n   <td style=\"text-align:right;\"> 1.3 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NASSAU COUNTY ICE TRAILER </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.3 </td>\n   <td style=\"text-align:right;\"> 13 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNIVERSITY MED CENTER OF EL PASO </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.2 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BREVARD COUNTY JAIL COMPLEX </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.2 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> AGUADILLA SPC </td>\n   <td style=\"text-align:left;\"> PR </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 1.2 </td>\n   <td style=\"text-align:right;\"> 26 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EL PASO LTAC HOSPITAL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.1 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PROMISE HOSPITAL </td>\n   <td style=\"text-align:left;\"> AZ </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.1 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ALVARADO PARKWAY INSTITUTE </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 1.0 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UCHEALTH UNV HOSP OF CO </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ANAHEIM GLOBAL MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MANATEE COUNTY DETENTION-ANNEX </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> VRK PRCS </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HARRIS COUNTY PSYCHIATRIC CENTER </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.9 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DADE CORRECTIONAL INST </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Dedicated </td>\n   <td style=\"text-align:right;\"> 0.8 </td>\n   <td style=\"text-align:right;\"> 11 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BUFFALO USBP HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.7 </td>\n   <td style=\"text-align:right;\"> 20 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> POLK COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.7 </td>\n   <td style=\"text-align:right;\"> 23 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LOUISVILLE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> KY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.7 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CBP MOVEMENT COORDINATION AREA </td>\n   <td style=\"text-align:left;\"> NA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.7 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FRANKLIN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> PA </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.6 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BROWN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> WI </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.6 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHAMPLAIN HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 8 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HOUSTON HEALTHCARE HOSP </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LOUDOUN COUNTY </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NORTHWEST REG. ADULT DET. </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WENTWORTH DOUGLAS HOSPITAL </td>\n   <td style=\"text-align:left;\"> NH </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> RAPID CITY HOLD ROOM </td>\n   <td style=\"text-align:left;\"> SD </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FRIO REGIONAL HOSPITAL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.5 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CLEVELAND HOLD ROOM </td>\n   <td style=\"text-align:left;\"> OH </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NASHVILLE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> TN </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 22 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BROWARD GENERAL MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNION COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> SD </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 9 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GLENWOOD SPRINGS HOLDROOM </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MEDFORD SUB-OFFICE </td>\n   <td style=\"text-align:left;\"> OR </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 14 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNIVERSITY HOSPITAL </td>\n   <td style=\"text-align:left;\"> NJ </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ALAMOSA HOLDROOM </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EUGENE HOLDROOM </td>\n   <td style=\"text-align:left;\"> OR </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MONROE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LOYOLA CENTER FOR HEALTH </td>\n   <td style=\"text-align:left;\"> IL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> TX HLTH HARRIS METH HOSP </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.4 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> LAREDO MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> NASSAU UNIV MED CTR </td>\n   <td style=\"text-align:left;\"> NY </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GRADY MEMORIAL HOSPITAL </td>\n   <td style=\"text-align:left;\"> GA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HIGHLAND MTN COR CTR </td>\n   <td style=\"text-align:left;\"> AK </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> DURANGO HOLDROOM </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 6 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ARROWHEAD REGIONAL MED CENTER </td>\n   <td style=\"text-align:left;\"> CA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MCLENNAN COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BOSTON SPC </td>\n   <td style=\"text-align:left;\"> MA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CENTRAL VA REGIONAL JAIL </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> VIRGINIA BEACH </td>\n   <td style=\"text-align:left;\"> VA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CAMPBELL COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> WY </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FLAGLER COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 12 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SUMTER COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.3 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> BANNER IRONWOOD MED CTR </td>\n   <td style=\"text-align:left;\"> AZ </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CRAIG HOLDROOM </td>\n   <td style=\"text-align:left;\"> CO </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PARKLAND HOSPITAL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WEST MIAMI DADE BAPT HEALTH EMERG </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> SALINE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> NE </td>\n   <td style=\"text-align:left;\"> Non-Dedicated </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ST ELIZABETH YOUNGSTOWN HOSPITAL </td>\n   <td style=\"text-align:left;\"> OH </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> UNIVERSITY MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> NV </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.2 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHARLESTON COUNTY CORRECT </td>\n   <td style=\"text-align:left;\"> SC </td>\n   <td style=\"text-align:left;\"> Federal </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> EL PASO COUNTY JAIL (TX) </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> PALM BEACH COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 4 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MOUNT NITTANY MEDICAL CENTER </td>\n   <td style=\"text-align:left;\"> PA </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> RIO GRANDE ST.HOSPITAL </td>\n   <td style=\"text-align:left;\"> TX </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 7 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> CHARLOTTE COUNTY JAIL </td>\n   <td style=\"text-align:left;\"> FL </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> ANCHORAGE SUB-OFFICE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> AK </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 5 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> GARDEN CITY PROCESSING @ FINNEY CO </td>\n   <td style=\"text-align:left;\"> KS </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HEL DISTRICT CUSTODY </td>\n   <td style=\"text-align:left;\"> MT </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.1 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> FORT SMITH HOLDROOM </td>\n   <td style=\"text-align:left;\"> AR </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> HENDERSONVILLE HOLD ROOM </td>\n   <td style=\"text-align:left;\"> NC </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 3 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> WICHITA HOLDROOM </td>\n   <td style=\"text-align:left;\"> KS </td>\n   <td style=\"text-align:left;\"> Hold/Staging </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> MARION CO JAIL </td>\n   <td style=\"text-align:left;\"> OR </td>\n   <td style=\"text-align:left;\"> Unclassified </td>\n   <td style=\"text-align:right;\"> 0.0 </td>\n   <td style=\"text-align:right;\"> 2 </td>\n  </tr>\n</tbody>\n</table></div>\n\n`````\n:::\n:::\n\n\n110 unreported facilities (Peak ≥ 2) were active in the Trump period but not the Biden period. Of these, 25 had ADP \\< 2 under Trump, contributing 1514 ADP in total.\n\n\n::: {#tbl-trump-only-by-type .cell tbl-cap='New unreported facilities under Trump (ADP ≥ 2), by type'}\n\n```{.r .cell-code}\nif (length(trump_only_codes) > 0) {\n  trump_unmatched |>\n    filter(detention_facility_code %in% trump_only_codes) |>\n    group_by(type_grouped) |>\n    summarise(\n      Facilities = n(),\n      `Total ADP` = round(sum(mean_pop)),\n      .groups = \"drop\"\n    ) |>\n    arrange(desc(`Total ADP`)) |>\n    kable(col.names = c(\"Facility type\", \"Facilities\", \"Total ADP\"))\n}\n```\n\n::: {.cell-output-display}\n\n\n|Facility type | Facilities| Total ADP|\n|:-------------|----------:|---------:|\n|Dedicated     |          2|       809|\n|Hold/Staging  |         27|       355|\n|Unclassified  |         60|       311|\n|Federal       |         12|        59|\n|Non-Dedicated |          8|        33|\n|Medical       |          1|         1|\n\n\n:::\n:::\n\n\n### Facilities active in both periods\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboth_codes <- intersect(biden_active$detention_facility_code,\n                         trump_active$detention_facility_code)\n\nboth_compare <- biden_unmatched |>\n  filter(detention_facility_code %in% both_codes) |>\n  select(detention_facility_code, detention_facility, state, type_grouped,\n         biden_adp = mean_pop, biden_peak = peak_pop) |>\n  inner_join(\n    trump_unmatched |>\n      filter(detention_facility_code %in% both_codes) |>\n      select(detention_facility_code,\n             trump_adp = mean_pop, trump_peak = peak_pop),\n    by = \"detention_facility_code\"\n  ) |>\n  mutate(\n    adp_change = trump_adp - biden_adp,\n    adp_pct_change = if_else(biden_adp == 0, NA_real_,\n                             (trump_adp / biden_adp - 1) * 100)\n  )\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(both_compare, aes(x = biden_adp, y = trump_adp, color = type_grouped)) +\n  geom_abline(slope = 1, intercept = 0, linetype = \"dashed\", alpha = 0.5) +\n  geom_point(alpha = 0.7) +\n  scale_x_log10(labels = comma) +\n  scale_y_log10(labels = comma) +\n  labs(x = \"Biden final quarter ADP\", y = \"Trump recent quarter ADP\",\n       color = \"Facility type\")\n```\n\n::: {.cell-output-display}\n![Mean ADP at unreported facilities: Biden vs Trump (facilities with ADP ≥ 2 in both periods, log scale)](index_files/figure-html/fig-scatter-periods-1.png){#fig-scatter-periods width=672}\n:::\n:::\n\n\n\n::: {#tbl-top-increases .cell tbl-cap='Top 15 unreported facilities by ADP increase (Biden → Trump)'}\n\n```{.r .cell-code}\nboth_compare |>\n  arrange(desc(adp_change)) |>\n  head(15) |>\n  transmute(\n    Facility = detention_facility, State = state, Type = type_grouped,\n    `Biden ADP` = round(biden_adp),\n    `Trump ADP` = round(trump_adp),\n    Change = round(adp_change)\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Facility                       |State |Type         | Biden ADP| Trump ADP| Change|\n|:------------------------------|:-----|:------------|---------:|---------:|------:|\n|DALLAS F.O. HOLD               |TX    |Hold/Staging |        16|       104|     88|\n|LOS CUST CASE                  |CA    |Hold/Staging |         7|        89|     82|\n|ATLANTA DIST. HOLD RM          |GA    |Hold/Staging |         9|        89|     80|\n|BROADVIEW SERVICE STAGING      |IL    |Hold/Staging |         9|        89|     80|\n|MONTGOMERY HOLD RM             |TX    |Hold/Staging |        30|        96|     66|\n|NYC HOLD ROOM                  |NY    |Hold/Staging |         5|        67|     62|\n|AZ REM OP COORD CENTER (AROCC) |AZ    |Hold/Staging |        16|        70|     54|\n|BALTIMORE HOLD ROOM            |MD    |Hold/Staging |         2|        47|     45|\n|WASHINGTON FIELD OFFICE        |VA    |Hold/Staging |         7|        44|     37|\n|MIAMI (MIRAMAR) HOLD ROOM      |FL    |Hold/Staging |         0|        35|     35|\n|SAN ANTONIO DRO HOLD ROOM      |TX    |Hold/Staging |         5|        36|     31|\n|RICHMOND SUB-OFFICE HOLD       |VA    |Hold/Staging |         5|        34|     29|\n|ORLANDO HOLD ROOM              |FL    |Hold/Staging |         6|        34|     28|\n|TAMPA HOLD ROOM                |FL    |Hold/Staging |         5|        33|     27|\n|SND DISTRICT STAGING           |CA    |Hold/Staging |         9|        35|     27|\n\n\n:::\n:::\n\n\n\n::: {#tbl-top-decreases .cell tbl-cap='Top 15 unreported facilities by ADP decrease (Biden → Trump)'}\n\n```{.r .cell-code}\nboth_compare |>\n  arrange(adp_change) |>\n  head(15) |>\n  transmute(\n    Facility = detention_facility, State = state, Type = type_grouped,\n    `Biden ADP` = round(biden_adp),\n    `Trump ADP` = round(trump_adp),\n    Change = round(adp_change)\n  ) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|Facility                          |State |Type          | Biden ADP| Trump ADP| Change|\n|:---------------------------------|:-----|:-------------|---------:|---------:|------:|\n|KROME HOLD ROOM                   |FL    |Hold/Staging  |        21|         0|    -21|\n|MCALLEN HOLD ROOM                 |TX    |Hold/Staging  |        13|         5|     -7|\n|PECOS HOLD ROOM                   |TX    |Hold/Staging  |         3|         1|     -1|\n|COLUMBIA CARE CENTER              |SC    |Unclassified  |         3|         2|     -1|\n|NEW/INS OS HOLD ROOM              |NJ    |Hold/Staging  |         1|         0|     -1|\n|CASPER HOLDROOM                   |WY    |Hold/Staging  |         0|         0|      0|\n|CHARLOTTE AMALIE HOLDROOM         |VI    |Hold/Staging  |         0|         0|      0|\n|BALDWIN COUNTY COR. CENTER        |AL    |Non-Dedicated |         2|         2|      0|\n|FAYETTEVILLE HOLD ROOM            |AR    |Hold/Staging  |         0|         0|      0|\n|LAS CRUCES HOLD ROOM              |NM    |Hold/Staging  |         0|         0|      0|\n|JACK HARWELL DETENTION CENTER     |TX    |Federal       |         0|         0|      0|\n|VALLEYWISE HEALTH MED CTR         |AZ    |Unclassified  |         0|         0|      0|\n|LEXINGTON PROCESSING @ FAYETTE CO |KY    |Unclassified  |         0|         0|      0|\n|ROCK ISLAND HOLD ROOM             |IL    |Hold/Staging  |         1|         1|      0|\n|TITUS COUNTY JAIL                 |TX    |Federal       |         0|         0|      0|\n\n\n:::\n:::\n\n\n### Daily unreported population by period\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(daily_unreported, aes(x = date, y = total_pop, fill = type_grouped)) +\n  geom_col() +\n  facet_wrap(~period, scales = \"free_x\") +\n  scale_y_continuous(labels = comma) +\n  scale_x_date(date_labels = \"%b %d\") +\n  labs(x = NULL, y = \"Unreported detained population\", fill = \"Facility type\")\n```\n\n::: {.cell-output-display}\n![Daily unreported detention population during both comparison periods, by facility type (ADP ≥ 2 facilities only)](index_files/figure-html/fig-daily-unreported-periods-1.png){#fig-daily-unreported-periods width=672}\n:::\n:::\n\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../site_libs/htmltools-fill-0.5.9/fill.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/htmlwidgets-1.6.4/htmlwidgets.js\"></script>\n<script src=\"../../site_libs/jquery-3.6.0/jquery-3.6.0.min.js\"></script>\n<link href=\"../../site_libs/leaflet-1.3.1/leaflet.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/leaflet-1.3.1/leaflet.js\"></script>\n<link href=\"../../site_libs/leafletfix-1.0.0/leafletfix.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/proj4-2.6.2/proj4.min.js\"></script>\n<script src=\"../../site_libs/Proj4Leaflet-1.0.1/proj4leaflet.js\"></script>\n<link href=\"../../site_libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/leaflet-binding-2.2.3/leaflet.js\"></script>\n<script src=\"../../site_libs/leaflet-providers-3.0.0/leaflet-providers.js\"></script>\n<script src=\"../../site_libs/leaflet-providers-plugin-2.2.3/leaflet-providers-plugin.js\"></script>\n<script src=\"../../site_libs/fuse_js-7.0.0/fuse_js-prod.js\"></script>\n<link href=\"../../site_libs/lfx-search-4.0.0/lfx-search-prod.css\" rel=\"stylesheet\" />\n<script src=\"../../site_libs/lfx-search-4.0.0/lfx-search-prod.js\"></script>\n<script src=\"../../site_libs/lfx-search-4.0.0/lfx-search-bindings.js\"></script>\n<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}