---
title: Welcome
description: The first draft of my welcome post for this website
author: Carwil Bjork-James
date: 13 October 2024
---

_This is how I first welcomed readers to this website. It's a post deeply 
shaped by grief over the Gaza genocide. I'm leaving it here as a record of my initial intentions for this space._

### Welcome

This research notes website is an experiment born of crisis and grief.
Expect it to change forms before it settles.

It's a space where I will witness planned cruelty and human tragedies with numbers and data.
Because my primary research project archives the death of nearly seven hundred Bolivians who
lost their lives in political struggle and I need somewhere to reflect on what that means.

Because weapons sent by my country's government are inflicting quantitatively far greater 
losses weekly and we need data to make sense of how. 

Because using numbers and maps and wrapping my head around the scale of things can dramatically
change how I view the world. And I can share those perspectives through data.

Because carefully presented evidence offers a path through the public denial that keeeps power intact.

And because these are the tools I've been training myself to use, and they won't fit on my other 
main spaces for public reflection, including my blog: [Carwil without Borders](https://woborders.blog/).

Lastly behind this data, there is a lot of death. I've chosen not to look away.